### ISSUE TITLE
Tomcat 8.0.20 Fails Startup

### ISSUE THREAD

**Issue by stevewallecs** [cloudfoundry/java-buildpack#166]
When using Tomcat 8.0.20, my application failed to start due to an out of memory exception. This worked with 8.0.18. I reverted back to 8.0.18 by explicitly specifying it in the tomcat.yml and the application was able to start.

**Comment by stevewallecs** [comment]
Also posted on stackoverflow - http://stackoverflow.com/questions/29169010/tomcat-8-0-20-out-of-memory-error

**Comment by cgfrost** [comment]
Hi, there was a similar issue known with a previous 8.0.x version of Tomcat but I believe that to be fixed in 8.0.20. I'm going to hold off raising this on our tracker until we've got a better idea if the problem is in CF or Tomcat. If it's Tomcat we can consider rolling back to 8.0.19 but that is a last resort. Thanks for raising the stackoverflow question.

**Comment by stevewallecs** [comment]
Agreed that it looks like a tomcat issue, since it occurs when during tomcat startup. Although I haven't tried deploying to a stand alone tomcat instance in my local environment. I'll give that a shot and see how it behaves.

**Comment by stevewallecs** [comment]
Installing Tomcat 8.0.20 on my CentOS release 6.6 (Final) the application did start. Maybe it has to do with the underlying Ubuntu OS?

**Comment by nebhale** [comment]
@markt-asf Is this something you've seen?  I guess I'm asking both as a bug report to you and whether we should be rolling back?

**Comment by markt-asf** [comment]
I'm not aware of any such memory issues with 8.0.20. Neither am I aware of any reason to revert to 8.0.18 rather than 8.0.20. Any OOME bug report is pretty much meaningless with an associated heapdump and analysis of the data it contains. It is certainly possible that an application that generates lots of temporary data during startup was on the cusp of an OOME with 8.0.18 and the 8.0.18 -> 8.0.20 delta was enough to tip it over the edge but - without hard data - that is little more than speculation on my part.

**Comment by nebhale** [comment]
@stevewallecs Based on Mark's statement there, I'm inclined to close this out with no changes.  We haven't had a rash of reports that .20 is causing problems, so it might simply be something about your application.  Have you tried upping the memory allocated to your Warden container (`cf scale <APP> -m <size>`)?

**Comment by stevewallecs** [comment]
It appears the .20 release required just a little more memory. I had my environment fairly tight on memory. Bumping it up just a little bit and things succeeded.
