### ISSUE TITLE
Can user update memory without restage the app?

### ISSUE THREAD

**Issue by df007** [cloudfoundry/java-buildpack#175]
Memory is calculated on compile phase, what will happen if user change the memory setting, and restart the app. 
E.g. an APP run on 2G memory, our code calculate the heap, stack,etc for JVM during compile phase. User set the memory to 4G, and restart the APP, will the new 2G be used?

**Comment by nebhale** [comment]
A `restage` is required because the calculation is so involved.  There is a [non-trivial amount of code](https://github.com/cloudfoundry/java-buildpack/tree/master/lib/java_buildpack/jre/memory) devoted to the proper calculation and in a Java environment, there is no guarantee of a Ruby runtime to run that code.  The three options we've identified are

1. Install a Ruby runtime into the droplet
1. Write a `go` based version of the same code and run it both at staging and start time
1. Require a `restage` to run the code as it currently exists

We've opted for #3, with a long-term plan to address #2.  However, since the community hasn't been particularly vocal about the need for a change from the status quo, the priority for getting #2 done is low.

**Comment by youngm** [comment]
@nebhale I hope you have me counted as one community member who doesn't like this. :)

For me this issue is the only major problem major problem I currently have with the Java Buildpack.  My users run into issues with this frequently.  I'm sure there are others in the community who don't like this functionality as well.  How many votes for a fix to this would be needed to count as being vocal?

That said the JBP is still great!  Keep up the good work.  You guys have done a great job addressing issues when you see the need and are ready to address them.  Hopefully you eventually see the need for this issue to be addressed.
