### ISSUE TITLE
Support for specifying java Xms different from Xmx

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#200]
I just upgraded to 3.1 and the upgrade went awesome.  I'm super excited about the new dynamic memory calculator.

However, I noticed that I had a customization in my buildpack fork that I'd forgot to mention before. :)

I set my configuration to use the G1GC and set `MinHeapFreeRatio` and `MaxHeapFreeRatio` by default.  This allows the VM to free DEA memory it is not using.  This great because it allows us to over commit the memory of our environments.

The new memory calculator always sets `Xms` the same as `Xmx` which may lend a minor performance improvement but doesn't help my over commit my memory.

I'd like to support some way to either customize or optionally completely remove `Xms` from what the memory calculator provides.

I'd be more than happy to create the PRs that do this.  I just thought I'd get some feedback first on a preferred approach.

Previously I just removed `-Xms` from our memory config.  But that may not be the best solution for large memory DEAs if java calculates default `Xms` based on machine memory size.

**Comment by cgfrost** [comment]
Hi,

You've convinced us of the merits of making Xms optional so feel free to create a pull request. I think this will need a change to the Memory Calculate (hows your GO). The buildpack will also need to accept an option that gets passed on as an option to the Memory calculator through the start command output from the release phase. Have you considered doing something similar for PermGen as well?

**Comment by youngm** [comment]
@cgfrost  My Go is serviceable. :)

I haven't considered PermGen but I can look into including it and/or metaspace if you'd accept it.  I'll do the research first to ensure I understand how both work in this situation.

I'm on vacation for the next couple of weeks I'll get to it within the month.

**Comment by cgfrost** [comment]
That's great. We'll be here when you get back, have a good break.

**Comment by youngm** [comment]
@cgfrost so after doing some research this is the approach I'm planning to take.

Leaving off Xms allows the JVM to propose a default based on how much memory the machine has.  In the case of Linux containers I believe the way it gets system memory provides it with the total memory of the DEA.  So in some tests.  On a 1 GB machine the Xms default is 16MB.  On a 20GB DEA the Xms default is 316MB.  316 is too beg of an Xms for my purposes.

So, I'd propose a parameter that allows the user to set a fixed Xms.  If the parameter value ends up being more than Xmx then set both to the same.  If no value is set for this parameter (the default) then set Xmx and Xms the same.

```
memory_calculator:
  memory_sizes:
    minimum_heap: 1MB
```
Something like that.

Thoughts?

I looked into doing the same thing for PermGen/metaspace and decided that for our purposes it wouldn't buy us much.  Most of our apps are Plain java apps not Groovy or something dynamic that creates and disposes permgen regularly.  So, I think the value here for my org is minimal.  Might be useful for someone else though.

**Comment by youngm** [comment]
@cgfrost I suppose another option would be to add a percentage to memory_heuristics.  I'd be fine with that as well:

```
memory_calculator:
  memory_heuristics:
    initial_heap: 5
```

**Comment by youngm** [comment]
@cgfrost on second thought I didn't notice till now that you were specifying Initial PermSize in addition to Max.  So, yes. I'd like to support a smaller initial PermSize/Metaspace.  I'm thinking I'll configure PerSize and Metaspace similar to to Xms.

**Comment by youngm** [comment]
@cgfrost After looking over the memory_calculator code I think I see what you were saying all along.

Perhaps provide a set of initial config processed in a completely different way than sizes and heuristics are.

```
memory_calculator:
  memory_initial:
    heap: 16m
    metaspace: 5m
    permgen: 5m
```

I'd have to process the initials to not exceed the maxes in the memory_calculator.  How does that sound?

**Comment by cgfrost** [comment]
Hi Mike, Thanks for all of this. I have discussed it with @Zteve and we will comment on the pull request later but in the mean time I'd like to discuss your approach.

We're leaning towards the use of percentages of the calculated maximum for initial values (subject to JVM minimums). You talk about basing percentages off the container memory instead so how do you feel about going from the calculated maximum. The default would be 100% which is effectively what happens today. You haven't really declared you favorite approach between the ones you have suggested, although your pull request is going down the route of absolute initial values. 

No matter how we specify the initial values I think it should get it's own `memory_initial` section in the buildpack config to make it clearer what's going on to other users. Will make it easier to document as well I think.

**Comment by youngm** [comment]
@cgfrost @Zteve Percentage of Max Heap sounds good.  I don't think it is significant which approach is taken.  As long as it allows me to free up system memory.  Setting a fixed value seemed simpler so that is the approach I took in the PR.  But, I wouldn't have a problem changing it to percentage of Max.  I look forward to your PR comments.  If I don't get any perhaps today I'll go ahead and change it to percentage of Maxs and let you comment on that.

**Comment by cgfrost** [comment]
Preserving the comments from https://github.com/cloudfoundry/java-buildpack/pull/159 do you think we should support a situation where no initial memory values are specified at all, so it's left to the JVM default. (I'm asking this while not knowing what the JVM default actually is)

**Comment by youngm** [comment]
@lhotari @cgfrost K, this issue just got a bit more complicated.  I ran some minimal value tests and this is what I found:

* -Xms0M
 * On java 7 is an error.  A value of 2M is accepted
 * On Java 8 it is accepted but appears to change it to the default as if no value specified
* -XX:MetaspaceSize=0M
 * Is an error 1M is accepted
 * The default appears to be 20M if no value specified regardless of server System memory
* -XX:PermSize=0M
 * Is an error 1M is accepted

So, given this new data I think I was on the wrong track with the current PR.  What we should probably do is:
* Provide an option to turn off specifying MetaspaceSize and PermSize as requested by @lhotari.  I'm good with a 20M as a default.  If MaxMetaspaceSize is set smaller the initial is changed to Max.
* Provide a way to specify initial size of -Xms as a percentage of -Xmx but either force a minimum of 2M and provide a warning.

So, what do you think config should look like for the proposal above?
```
memory_calculator:
  memory_initial:
    heap: 5%
    metaspace: false
    permgen: false
```

**Comment by youngm** [comment]
@lhotari are you aware of a difference between setting a small Metaspace value vs no value at all?  If a small metaspace value is acceptable then perhaps we can keep a 3 % but set a minimum of 1M for metaspace and permgen similar to heap?

**Comment by lhotari** [comment]
@youngm I guess that would work. "The default size of `MetaspaceSize` is platform-dependent and ranges from 12 MB to about 20 MB." says the Oracle documentation.

The Oracle documentation about [Class Metadata](http://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/considerations.html#sthref66):
<blockquote>
Class metadata is deallocated when the corresponding Java class is unloaded. Java classes are unloaded as a result of garbage collection, and garbage collections may be induced in order to unload classes and deallocate class metadata. When the space committed for class metadata reaches a certain level (a high-water mark), a garbage collection is induced. After the garbage collection, the high-water mark may be raised or lowered depending on the amount of space freed from class metadata. The high-water mark would be raised so as not to induce another garbage collection too soon. <b>The high-water mark is initially set to the value of the command-line option `MetaspaceSize`.</b> It is raised or lowered based on the options `MaxMetaspaceFreeRatio` and `MinMetaspaceFreeRatio`. If the committed space available for class metadata as a percentage of the total committed space for class metadata is greater than `MaxMetaspaceFreeRatio`, then the high-water mark will be lowered. If it is less than `MinMetaspaceFreeRatio`, then the high-water mark will be raised.
</blockquote>
<blockquote>
Specify a higher value for the option `MetaspaceSize` to avoid early garbage collections induced for class metadata. The amount of class metadata allocated for an application is application-dependent and general guidelines do not exist for the selection of `MetaspaceSize`. The default size of `MetaspaceSize` is platform-dependent and ranges from 12 MB to about 20 MB.
</blockquote>

This doc explains that `MetaspaceSize` parameter is for tuning the "high-water mark" used for Class Metadata garbage collection (which is not the same as heap GC). It's not for pre-allocating the metaspace. That's what I was trying to explain in the previous issue #159.

**Comment by youngm** [comment]
@cgfrost a quick status check.  Are these PRs still good to merge at some point?  Are you waiting for me to provide anything?

* https://github.com/cloudfoundry/java-buildpack-memory-calculator/issues/1
* https://github.com/cloudfoundry/java-buildpack/issues/210

**Comment by nebhale** [comment]
@youngm @cgfrost and I haven't forgotten about you :smile:.  We're all hands on deck for a customer requirement at the moment, but will be back for your contributions as soon as that's done.  Sorry for the radio silence on this.

**Comment by youngm** [comment]
@nebhale sounds good.  I'll try and be patient. :)

**Comment by cgfrost** [comment]
@youngm Ley me know if your happy to close this one off. Re: https://github.com/cloudfoundry/java-buildpack/commit/83b743a23f9aeaa3fa3d34fefbd18d90e877e0f9

**Comment by youngm** [comment]
I'm happy thanks for your help working through this solution.

**Comment by cgfrost** [comment]
That's great, thanks @youngm
