### ISSUE TITLE
Incorrect name - change name from app-dynamics to appdynamics

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/java-buildpack#214]
I am a software engineer at AppDynamics and have been working closely with the developments that we have been doing with Pivotal Cloud Foundry. 

I have noticed that the name of the AppDynamics service is incorrect. As mentioned here (https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-app_dynamics_agent.md#user-provided-service) the name of the user defined service should have "app-dynamics" in it. This is incorrect name. It should actually be "appdynamics". Though, I do understand that this issue is small, but it does irk many customers/developers at AppDynamics. 

I tried to solve this issue by renaming the string in all relevant files from "app-dynamics" to "appdynamics" in my customized buildpack(https://github.com/nkatre/java-buildpack) but then I faced with the following error
![1__vim](https://cloud.githubusercontent.com/assets/6249847/9315521/74a16ace-44e4-11e5-822d-c6d7759de8da.png)

If I run the example app(spring-music) using cloud foundry buildpack, I noticed that the AppDynamics agent is downloaded successfully from the following location
![2__vim](https://cloud.githubusercontent.com/assets/6249847/9315585/cf92bcd0-44e4-11e5-8c05-20315f14eabd.png)

This indicates that the server URI is populated from cups service name. It would be really great if two things are taken care of from Pivotal end.
1. Making sure that the cups service is created by "appdynamics" name instead of "app-dynamics"
2. Also wanted to know if I can specify my aws s3 box link for agent download instead of downloading it from https://download.run.pivotal.io/app-dynamics/app-dynamics-4.0.7_0.zip ?
If yes, then where can I specify this in the buildpack ?
3. How to go about offering different services(plans) through service broker. If I already have service-broker code, how can I make it a part of Pivotal Web Services (specifically) ?

**Comment by cgfrost** [comment]
Hi,

I don't think name changing is going to be a high priority for is. The existing names are derived from existing naming conventions used throughout our code base. i.e. `AppDynamics` becomes `app-dynamics` in lower case. The alternative would be to use `Appdynamics` as the uppercase name in order to derive `appdynamics` as a lower case value. This would then result in console messages about the `... Appdynamics Agent ...`. We actually programmatically depend on the naming convention in some places. Also, we can't remove/rename already published dependencies as this would break existing deployments using AppDynamics. Using a different dependency (even if it's just a slight name change) would probably be more confusing to users as it would require a second config file and a second set of framework code in the buildpack to support it for future versions.

The ` https://download.run.pivotal.io` part of the url is configured in the buildpack by the config property `default.repository.root` from the `config/repository.yml` file. This is then used to build the full path in the `config/app_dynamics_agent.yml` config file (The name of this config file is again derived from the name of a Ruby class definition). Please look at the top level readme for information on how to supply new configuration to the buildpack through environment variables to change this configuration. No forking required.

As for your third point, I can't help you there. Provided additional service through PWS is beyond the scope of the Buildpack team. If you don't have any other contacts in Pivotal please let me know and I will try to help.

**Comment by nkatre** [comment]
Hello Christopher,

Thanks for your reply. Appreciate it.
In that case, would you be able to change the name to the alternate solution that you mentioned (i.e use *Appdynamics* as the uppercase name in order to derive *appdynamics* as a lower case value) 

Would you be able to make the changes with the current build pack and then integrate the changes, and change the top level README file. That would really serve the purpose.

Appreciate your help !

**Comment by cgfrost** [comment]
Hi,
I looked at this today to start work on it and I have realized that while I can change the Readme and the console message I can't change the name of the class in the Ruby code without causing a change to the resources directory name and the configuration file name. Doing either of those would constitute a breaking change and we've (both Pivotal and AppDynamics) got lots of paying customers with hundreds of apps in production that would need to make changes to those apps to handle this change. I'm really against breaking backwards compatibility for appearances sake. We've had support for AppDynamics for about 2 years and hopefully there are many more people using that support that we don't know about. If I make the full change there apps will just stop working one day and they will have to go and read the release notes to figure out what changed, this would be really bad. I've done the changes that can be done without causing an issue to existing deployments.

Git Commit: https://github.com/cloudfoundry/java-buildpack/commit/103fc4ad819e80391d585587b184f6ceda1bc4af

Tracker Issue: https://www.pivotaltracker.com/story/show/102165010

**Comment by nebhale** [comment]
This change is incomplete.

**Comment by cgfrost** [comment]
@nebhale What is missing?

**Comment by nebhale** [comment]
1. The change to the `README` only changes one of the two links. That change, and the change to the filename, should be reverted (the documentation filename should stay matching the configuration and ruby file).
1. The service `FILTER` should be expanded to support both `app-dynamics` and `appdynamics`.  Regex can be `/app[-]?dynamics/`.  Documentation should also be updated to reflect this change.

**Comment by cgfrost** [comment]
This issue has been addressed in a number of recent commits. Please reopen if you feel we have missed something that won't cause backwards compatibility issues.
