### ISSUE TITLE
AppDynamics - Request to change default tiername

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/java-buildpack#223]
Hello,

The following are the changes, if incorporated would be helpful to effectively understand AppDynamics configuration wrt PCF

**Change in default tier name**
 The default tier name currently specified [here](https://github.com/cloudfoundry/java-buildpack/blob/master/config/app_dynamics_agent.yml) is  **CloudFoundry**, which should be changed to

> default_tier_name: ! '$(expr "$VCAP_APPLICATION" : ''.\*application_name[": ]\*\([[:digit:]]\*\).\*'')'

Thus, the application name in the PCF world would map to tier_name in the AppDynamics world, which should ideally be the case.

**Comment by nebhale** [comment]
https://www.pivotaltracker.com/story/show/102469346

**Comment by nkatre** [comment]
Hi Ben,

I apologize for the long description, but some details had to be mentioned.

The below are the details that we at AppDynamics are proposing. These changes are proposed keeping in mind, customers who use AppDynamics service on PCF through CUPS as well as through Service Broker Tile.

> **Background on Service Broker AppDynamics Tile:**
>  We have the AppDynamics service broker tile ready which provides configuration for the following parameters
>  ![Config Parameters](http://postimg.org/image/hlmuolnad/)
>  The configuration for `application, tier and node name` (all in context of AppDynamics) are not configured manually unlike in appdynamics cups service. Thus we propose to populate these parameters through the following changes
 
 1. Application Name (in context of AppDynamics)
First, we check if the value is specified in `credentials['application-name']`  [handles cups use-case]
If not, then secondly, we check if an env variable called `APPDYNAMICS_APP_NAME` is set using `cf set-env`  [handles cups as well as sb tile use case]
If not then thirdly, we simply map the application name (in context of ApppDynamics) to application name(in context of PCF) through VCAP_APPLICATION  [handles cups as well as sb tile use case]
 2. Tier Name (in context of AppDynamics)
 First, we check if the value if specified in `credentials['tier-name']`  [handles cups use-case]
 If not, then we simply map the tier name (in context of ApppDynamics) to application name(in context of PCF) through VCAP_APPLICATION  [handles cups as well as sb tile use case]. This is useful in case of single-tier web applications as the tier and application (in context of AppDynamics) name will be same in the AppDynamics controller.
 3. Node Name (in context of AppDynamics)
 First, we check if the value if specified in `credentials['node-name']`  [handles cups use-case]
 If not, we will map the node name (in context of ApppDynamics) to instance_index(in context of PCF) through VCAP_APPLICATION  [handles cups as well as sb tile use case]
 However, I am not able to capture the instance_index during the staging phase and it needs to be done dynamically.

The customized buildpack file with all the above mentioned changes is [here](https://github.com/Appdynamics/java-buildpack/blob/master/lib/java_buildpack/framework/app_dynamics_agent.rb)
The additions/changes made to the original buildpack file are indicated by `# CHANGE` tag inside the file. Please look for this tag to understand what changes have been done to the original buildpack file.

I tried to populate the node_name using the default_node_name mentioned [here](https://github.com/Appdynamics/java-buildpack/blob/master/config/app_dynamics_agent.yml) but it didn't work. I reckon that there is some mistake in the syntax for evaluating the expression of default_node_name as seen in the last line of the image below.
![image](http://postimg.org/image/h6h9yj7wp/)
 If this is not the problem, then how would I dynamically populate the node_name with instance_index.

Also, could you confirm whether the changes are relevant and would be integrated in the PCF Java buildpack ?

**Comment by nebhale** [comment]
Other than the changes that we've discussed with respect to `tier-name` I wouldn't expect any changes from the buildpack at all.  At the moment, you can already set everything you describe:

1. [Application Name](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/app_dynamics_agent.rb#L62-L66)
  1. `credentials[`application-name']`
  1.  `cf set-env APP JBP_APP_DYNAMICS_AGENT 'default_application_name: FOO'`
  1. `config/app_dynamics_agent.yml/default_application_name`
  1. `VCAP_APPLICATION/application_name`
1. [Tier Name](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/app_dynamics_agent.rb#L99-L102)
  1. `credentials['tier-name']`
  1. `cf set-env APP JBP_APP_DYNAMICS_AGENT 'default_tier_name: FOO'`
  1. `config/app_dynamics_agent.yml/default_tier_name`
  1. `VCAP_APPLICATION/application_name`  _(this one needs to be added)_
1. [Node Name](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/app_dynamics_agent.rb#L84-L87)
  1. `credentials['node-name']`
  1. `cf set-env APP JBP_APP_DYNAMICS_AGENT 'default_node_name: FOO'`
  1. `config/app_dynamics_agent.yml/default_node_name`
  1. `VCAP_APPLICATION/instance_index`

The only difference between your submission and what already exists is the name of the environment variables used to set each parameter.  Since we already have a uniform way of setting these values, we'll favor that over one-off environment variables for components.

**Comment by cgfrost** [comment]
This change has been done in commit https://github.com/cloudfoundry/java-buildpack/commit/69abec6d2726f73a22339caa6ae7739f060002e4

The implementation isn't as demonstrated but it will result in the desired behavior.
