### ISSUE TITLE
Quotes not properly escaped in JBP_CONFIG_JAVA_MAIN?

### ISSUE THREAD

**Issue by ericbottard** [cloudfoundry/java-buildpack#227]
When passing values which contain quotes (both single and double) in JBP_CONFIG_JAVA_MAIN, my app does not start at all:
```
o-reconfiguration-1.10.0_RELEASE.jar (0.2s)
2015-09-08T15:27:49.90+0200 [STG/8]      OUT -----> Uploading droplet (57M)
2015-09-08T15:27:56.08+0200 [DEA/8]      OUT Starting app instance (index 0) with guid 843ab3ff-1fa2-48a1-8971-f7ed9de21cd3
2015-09-08T15:27:58.86+0200 [DEA/8]      ERR Instance (index 0) failed to start accepting connections
2015-09-08T15:27:58.87+0200 [API/1]      OUT App instance exited with guid 843ab3ff-1fa2-48a1-8971-f7ed9de21cd3 payload: {"cc_partition"=>"default", "droplet"=>"843ab3ff-1fa2-48a1-8971-f7ed9de21cd3", "version"=>"7d2db2f1-3364-448d-acf2-de315c1b97fc", "instance"=>"5ed264b922c9408692fe70955190410a", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1441718878}
2015-09-08T15:27:58.87+0200 [API/0]      OUT App instance exited with guid 843ab3ff-1fa2-48a1-8971-f7ed9de21cd3 payload: {"cc_partition"=>"default", "droplet"=>"843ab3ff-1fa2-48a1-8971-f7ed9de21cd3", "version"=>"7d2db2f1-3364-448d-acf2-de315c1b97fc", "instance"=>"5ed264b922c9408692fe70955190410a", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1441718878}
```

Excerpt from `cf env`:

Using a double quote
```
User-Provided:
JBP_CONFIG_JAVA_MAIN: {arguments: '--args.0.spring.cloud.stream.bindings.input=foo.0 --args.0.spring.cloud.stream.bindings.output=foo.1
    --modules=org.springframework.cloud.stream.module:filter-processor:jar:1.0.0.BUILD-SNAPSHOT
    --args.0.expression=payload.charAt(payload.length())=="0" '}
```

Using a single quote (note it has been properly yaml escaped)
```
JBP_CONFIG_JAVA_MAIN: {arguments: '--args.0.spring.cloud.stream.bindings.input=foo2.0 --args.0.spring.cloud.stream.bindings.output=foo2.1
    --modules=org.springframework.cloud.stream.module:filter-processor:jar:1.0.0.BUILD-SNAPSHOT
    --args.0.expression=payload.contains(''a'') '}
```

(For the record, the piece of code that produces said value is at https://github.com/spring-cloud/spring-cloud-dataflow/blob/3f4eee406d3e9059e4f565cfabfc6e7a993c31dc/spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryModuleDeploymentConverter.java#L66-L87)

**Comment by cgfrost** [comment]
Please do use square brackets so that it's being passed as an array and not an object with properties. As the value passed to `arguments` contains special characters I have placed it in double quotes. Your example above shows an odd `‘` char at the end, I'm assuming that's there in error. 

This is the value you can use in a manifest file, if you supply it at the command line you will need slightly different escaping as the command shell gets look in before passing it to the `cf` cli program.
```
    JBP_CONFIG_JAVA_MAIN: '[arguments: "--args.0.spring.cloud.stream.bindings.input=foo.0 --args.0.spring.cloud.stream.bindings.output=foo.1 --modules=org.springframework.cloud.stream.module:filter-processor:jar:1.0.0.BUILD-SNAPSHOT --args.0.expression=payload.charAt(payload.length())==''0''" ]'
```

Once the application has started `cf env myapp` gives the following value.

```
User-Provided:
JBP_CONFIG_JAVA_MAIN: [arguments: "--args.0.spring.cloud.stream.bindings.input=foo.0 --args.0.spring.cloud.stream.bindings.output=foo.1 --modules=org.springframework.cloud.stream.module:filter-processor:jar:1.0.0.BUILD-SNAPSHOT --args.0.expression=payload.charAt(payload.length())=='0'" ]
```

Can you tell me how you are supplying these environment variables to CF, manifest, command line or programmatically.

**Comment by ericbottard** [comment]
> Your example above shows an odd ‘ char at the end, I'm assuming that's there in error.

yes, sorry, this is from copying from Slack. I edited the issue.

As stated above, this is generated as some piece of Yaml (from java code). Hence the proper escaping of single quotes for example. See [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/3f4eee406d3e9059e4f565cfabfc6e7a993c31dc/spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryModuleDeploymentConverter.java#L66-L87).

Which brings me to my next point:
> Please do use square brackets so that it's being passed as an array and not an object with properties

Can you point me to where this is actually read in the buildpack code (although I'm no ruby guru), because I don't see how this can be interpreted. Is the whole thing supposed to be yaml, or just the value of say, the `arguments` mapping? I assume the former, given ["The value of the variable should be valid inline yaml"](https://github.com/cloudfoundry/java-buildpack/blob/f062497a96f146b3cca74c5ccd07fa4ac93fd23c/README.md#configuration-and-extension). 

`[foo: bar]` makes no sense to me (this would be a one-element array containing a (one-element) hash with key 'foo')
Notice however that [{foo: bar}](http://yaml-online-parser.appspot.com/?yaml=%7Bfoo%3A+bar%7D&type=json) is the same as [foo: bar](http://yaml-online-parser.appspot.com/?yaml=foo%3A+bar&type=json)

I'll try it nevertheless, but I don't see what this has to do with quotes. My code snippet is responsible for the generation of the yml bit, so currently not sure if I can tell it to use double quotes instead of single, but how would you pass a value with double quotes? My two examples above were **results**, as they appear in `cf env`, sorry if this was not clear

**Comment by cgfrost** [comment]
The code that merges user provided config with the existing config in the config files is a little complex but it's easy to see we are treating hashes and arrays separately. Multi line and inline yaml do have slightly different syntax's. See: https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/util/configuration_utils.rb#L118

The former is correct, the entire value of the environment variable has to be valid yaml. From `[argum....` to `....''0''" ]`

The single quotes around the whole thing are there because I'm showing an example where it's given in a manifest file, which is also yaml. The outer single quotes make the manifest treat the value of the environment variable as a String so that it get passed through to the buildpack for it to process. You won't need them if your passing this as a String over an API.

**Comment by cgfrost** [comment]
Actually, having just read the code. You should be able to pass a single argument with no brackets at all, so something like this if I was to define it in Java code.
```
String myConfig = "arguments: \"--args.0.spring.cloud.stream.bindings.input=foo.0 --args.0.spring.cloud.stream.bindings.output=foo.1 --modules=org.springframework.cloud.stream.module:filter-processor:jar:1.0.0.BUILD-SNAPSHOT --args.0.expression=payload.charAt(payload.length())==''0''\""
```
Notice I'm now escaping the double quotes to keep Java happy.

**Comment by cgfrost** [comment]
We've been talking about inline Yaml but in the Yaml spec we're actually talking about `flow` style instead of the usual `block` style Yaml. If this has misled you I'm sorry. Part of the definition of flow style yaml is that it's give as an array instead of a multiline line in the usual block style. The Wikipedia page explains it a little better (it talks about inline rather than flow) but doesn't go in to much detail. https://en.wikipedia.org/wiki/YAML#Lists

**Comment by cgfrost** [comment]
Since there's been no response on this issue for a week now, I'm going to close it. If you'd like to see it re-opened, please comment on the issue explaining what is unresolved.
