### ISSUE TITLE
war with only jsp and no classes does not detect

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/java-buildpack#244]
a war without classes but with a jsp failed to get detected by the java buildpack

```
$ jar -tf RedWeb.war
META-INF/MANIFEST.MF
META-INF/
WEB-INF/
WEB-INF/classes/
WEB-INF/lib/
index.jsp
```
and it results in the following when trying to push

```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (797B)
Downloading java_buildpack...
Downloaded java_buildpack
Downloaded buildpacks
Staging...
-----> Java Buildpack Version: v3.3.1 | https://github.com/cloudfoundry/java-buildpack.git#063836b
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: No container can run this application. Please ensure that you’ve pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
No container can run this application. Please ensure that you’ve pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed
```

however, this one does get detected properly just by adding a simple test servlet

```
$ jar -tf RedWeb.war
META-INF/MANIFEST.MF
META-INF/
WEB-INF/
WEB-INF/classes/
WEB-INF/classes/test/
WEB-INF/classes/test/TestServlet.class
WEB-INF/lib/
index.jsp
```

this seems unexpected

**Comment by nebhale** [comment]
Yup, unexpected.  We'll take a look.

**Comment by nebhale** [comment]
@jbayer Just added an explicit test that passes without modification to the code.  Seems like we'll need to take a look at that WAR specifically.  I'll bet it's got a wonky `MANIFEST.MF`.

**Comment by jbayer** [comment]
ok, i created it with STS with the Dynamic Web new project wizard, added a JSP, then exported as war. that's it. i'll send it to you. you can see the issue with:

`cf push jamesjsp -p /tmp/JspWeb.war -b java_buildpack`

**Comment by nebhale** [comment]
OK, I've [added some diagnostics](https://github.com/cloudfoundry/java-buildpack/compare/a2a184c...c71590e) that will help this in the future (and arguably should always have been there).  I've created a Gist with the new debug output for both [your WAR](https://gist.github.com/nebhale/83f3f37f81b789c88c33#file-jspweb-war-L22) and our [test application WAR](https://gist.github.com/nebhale/83f3f37f81b789c88c33#file-web-application-1-0-0-build-snapshot-war-L31).

In the listing of the contents of the application based on your WAR, you'll notice that the `WEB-INF/` directory is missing.  You'll notice that that's more or less [the only thing](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#tomcat-container) that the Tomcat container can trigger on.  It turns out that the existence of that directory is the only thing required for a file to be a "standard WAR".

So by the time the buildpack is presented with the filesystem, your application is no longer a standard WAR file.  I believe that this is a bug in the CLI.  Would you like to open the issue or shall I?

**Comment by jbayer** [comment]
it would help me out if you could open the cli issue with your diagnostics @nebhale , let me know if you need me to jump back in, but i'd appreciate it.

@dkoper heads up what we believe is a CLI upload issue coming your way

**Comment by nebhale** [comment]
Closed in lieu of https://github.com/cloudfoundry/cli/issues/676.
