### ISSUE TITLE
push fails with v3.3 java buildpack

### ISSUE THREAD

**Issue by thomasmey** [cloudfoundry/java-buildpack#253]
Hi,

with javabuildpack v3.3 fails to start my java app with `-m 64` option, the error is:

```
-----> Downloaded app package (1012K)
-----> Downloaded app buildpack cache (44M)
-----> Java Buildpack Version: v3.3 | https://github.com/cloudfoundry/java-buildpack.git#378f420
-----> Downloading Open Jdk JRE 1.8.0_65 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.3s)
-----> Downloading Open JDK Like Memory Calculator 2.0.1_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.1_RELEASE.tar.gz (found in cache)
       Cannot balance memory: Memory allocation failed for configuration: [metaspace:64M..], : Cannot allocate memory to 'heap' type
[Buildpack]                      ERROR Compile failed with exception RuntimeError
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed
```

my java app work with a previous javabuild pack, but I don't know the exact version, but I think it didn't include the memory calculator stuff.

how to disable the memory calcuator?

**Comment by thomasmey** [comment]
okay, with build pack 3.3 my app needs now as a minimum 128m, i.e. the memory usage doubled, double cost :-(

log of push is:

-----> Downloaded app package (1012K)
-----> Downloaded app buildpack cache (44M)
-----> Java Buildpack Version: v3.3 | https://github.com/cloudfoundry/java-buildpack.git#378f420
-----> Downloading Open Jdk JRE 1.8.0_65 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.3s)
-----> Downloading Open JDK Like Memory Calculator 2.0.1_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.1_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xms54613K -Xmx54613K -XX:MaxMetaspaceSize=64M -Xss568K -XX:MetaspaceSize=64M

-----> Uploading droplet (45M)

1 of 1 instances running

App started

**Comment by thomasmey** [comment]
So this commit seems to be the cause of this problem:
https://github.com/cloudfoundry/java-buildpack/commit/9393dc1a8262686769f342bc02c1e696c8253374

I was able to run with 64mb again by going back to v3.0 with:

cf push appname -m 64mb -p target/app.jar -b https://github.com/cloudfoundry/java-buildpack#v3.0

sadly the memory configurator uses a lot of memory and I wasn't able to disable it via set-env JBP_CONFIG_OPEN_JDK_JRE, or is this possible?

**Comment by nebhale** [comment]
The problem isn't actually with the buildpack or that particular commit.  Rather the memory calculator now properly flags illegal configurations.

```
  memory_sizes:
    heap: 
    metaspace: 64m..
    native: 
    permgen: 64m..
    stack: 
  memory_heuristics:
    heap: 75
    metaspace: 10
    native: 10
    permgen: 10
    stack: 5
  memory_initials:
    heap: 100%
    metaspace: 100%
    permgen: 100%
```

You'll notice in the [configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml#L26-L41) (excerpted above) that the memory configuration states that no less than `64m` of memory *must* be dedicated to `metaspace`.  If you've only given your container `64m` in the first place, then there is no way to allocate memory to any of the other, required, memory regions.  This has been [the case since April 30th, 2015](https://github.com/cloudfoundry/java-buildpack/blame/master/config/open_jdk_jre.yml#L28).  The only change then is that before, applications might unexpectedly fail some time after start.  Now, applications are prevented from starting with obvious errors like this.

If you'd like to run an application in only `64m`, you'll need to update your `memory_sizes` (using `JBP_CONFIG_OPEN_JDK_JRE` if you choose) to [properly allocate](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory) that little memory.

**Comment by thomasmey** [comment]
Hi,

okay. Thanks for the hint, I'll try that. Many thanks
