### ISSUE TITLE
Offline build pack creation is not working

### ISSUE THREAD

**Issue by jrsaravanan** [cloudfoundry/java-buildpack#254]
We are trying to create offline build back using `bundle exec rake package OFFLINE=true` it is failing 
ruby 2.0.0p353 (2013-11-22) [x86_64-linux]

```
[root@ java-buildpack]# bundle exec rake package OFFLINE=true
rake aborted!
Invalid micro version '0.0'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/tokenized_version.rb:112:in `micro_and_qualifier'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/tokenized_version.rb:39:in `initialize'
/root/workarea/apps/java-buildpack/lib/java_buildpack/repository/version_resolver.rb:42:in `new'
/root/workarea/apps/java-buildpack/lib/java_buildpack/repository/version_resolver.rb:42:in `block in resolve'
/root/workarea/apps/java-buildpack/lib/java_buildpack/repository/version_resolver.rb:41:in `map'
/root/workarea/apps/java-buildpack/lib/java_buildpack/repository/version_resolver.rb:41:in `resolve'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:203:in `version'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:171:in `block in get_from_cache'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:53:in `call'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:53:in `block in cached'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:53:in `open'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:53:in `open'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:53:in `cached'
/root/workarea/apps/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:74:in `get'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:169:in `get_from_cache'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:161:in `block (2 levels) in uris'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:159:in `each'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:159:in `block in uris'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:158:in `each'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:158:in `uris'
/root/workarea/apps/java-buildpack/rakelib/dependency_cache_task.rb:45:in `initialize'
/root/workarea/apps/java-buildpack/Rakefile:40:in `new'
/root/workarea/apps/java-buildpack/Rakefile:40:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by nebhale** [comment]
As the errors message states, the version that you're trying to download is invalid.  All versions must have at least three components, a major, a minor, and a micro.  Expanding the offending version by appending a `.0` to it will fix the issue.

**Comment by ChandraNarayanasamy** [comment]
Hi Ben:

We have not done any changes to buildpack but we have a network error (it seems our internal proxy is blocking some outgoing connection) so in order to over come that we thought of building our own build pack in offline mode.

The error we are getting is as follows. Is there any setting we need to do to overcome this?

Starting app web-application in org <our company name>.com / space dev as admin...
-----> Downloaded app package (158M)
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': Failed to connect to 10.x.x.x <masked the IP> port 8080: Connection refused
Cloning into '/tmp/buildpacks/java-buildpack'...
fatal: unable to access 'https://github.com/cloudfoundry/java-buildpack.git/': Failed to connect to 10.x.x.x port 8080: Connection refused

Thanks in advance for your help.

**Comment by nebhale** [comment]
Cloud Foundry comes with the Java Buildpack already installed so that you do not need traverse the network to download it.  If you run `cf buildpack`, you'll see a list of the candidate buildpacks available to you:

```shell
$ cf buildpacks
Getting buildpacks...

buildpack              position   enabled   locked   filename   
staticfile_buildpack   1          true      false    staticfile_buildpack-cached-v1.2.2.zip   
java_buildpack         2          true      false    java-buildpack-v3.3.1.zip   
ruby_buildpack         3          true      false    ruby_buildpack-cached-v1.6.8.zip   
nodejs_buildpack       4          true      false    nodejs_buildpack-cached-v1.5.2.zip   
go_buildpack           5          true      false    go_buildpack-cached-v1.6.3.zip   
python_buildpack       6          true      false    python_buildpack-cached-v1.5.1.zip   
php_buildpack          7          true      false    php_buildpack-cached-v4.2.1.zip   
liberty_buildpack      8          true      false    liberty_buildpack.zip   
binary_buildpack       9          true      false    binary_buildpack-cached-v1.0.1.zip   
```

You can use the name of any of those buildpacks (yours are likely to be different than that list) with the `-b` argument or `buildpack` key in a manifest.

```
$ cf push <APP> -p <JAR-FILE> -b java_buildpack`
```

**Comment by jrsaravanan** [comment]
We tried  
[root@hello web-application]# cf push web-application -p build/libs/web-application-1.0.0.BUILD-SNAPSHOT.war -b java_buildpack

Updating app web-application in org jio.com / space dev as admin...
OK

Uploading web-application...
Uploading app files from: build/libs/web-application-1.0.0.BUILD-SNAPSHOT.war
Uploading 5.5M, 36 files
Done uploading
OK

Stopping app web-application in org jio.com / space dev as admin...
OK

Starting app web-application in org jio.com / space dev as admin...
-----> Downloaded app package (14M)
[DownloadCache]                  WARN  Unable to download https://download.run.pivotal.io/memory-calculator/trusty/x86_64/index.yml into cache /tmp: Connection refused - connect(2)
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Open JDK Like Memory Calculator error: Unable to find cached file for https://download.run.pivotal.io/memory-calculator/trusty/x86_64/index.yml>
Open JDK Like Memory Calculator error: Unable to find cached file for https://download.run.pivotal.io/memory-calculator/trusty/x86_64/index.yml
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

**Comment by nebhale** [comment]
That's because the version of the buildpack you're trying to use requires an outbound connection to the internet.  If you cannot acquire that, you'll need to use an offline buildpack. Offline versions of the buildpack can be found [attached to each release](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.3.1).  You'll need to use the [`cf create-buildpack` command](http://docs.cloudfoundry.org/adminguide/buildpacks.html) to upload it.

**Comment by jrsaravanan** [comment]
@nebhale  Thank you.
since it is version issue , closing the thread.
