### ISSUE TITLE
Postgres JDBC driver is not downloaded in case of multiple postgres service bindings

### ISSUE THREAD

**Issue by SvetlinZarev** [cloudfoundry/java-buildpack#265]
Hello!

The java buildpack is not downloading the PostgreSQL driver if there are multiple postgresql services bound to my application. If there is only one postgres service bound - then everything is fine and the buildpack downloads the driver.  Is this intentional ? 

Kind regards,
Svetlin

**Comment by nebhale** [comment]
It is [by design](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/postgresql_jdbc.rb#L52) although whether it's a good design could be debated.  In the end, both this and the MySQL/MariaDB support are oriented towards "first run" experience.  I'd highly recommend you packaging a JAR of your own rather than depending on ours.  In that setup you're in control as to exactly what version of the JAR is in your application and can change it as you see fit, rather than being reliant on what the buildpack does.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
