### ISSUE TITLE
JMX Docs Issue

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/java-buildpack#266]
I don't believe that this statement is correct.

>The `LOCAL_PORT` can be any open port on your computer, but typically matches the `REMOTE_PORT` where possible.

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-jmx.md#creating-ssh-tunnel

I think that `LOCAL_PORT` will need to match the `REMOTE_PORT`.  If you change `LOCAL_PORT` to something different the JMX connection will succeed, but the RMI connection will fail, because it does match `com.sun.management.jmxremote.rmi.port`.

Ultimately it would be cool if you could set `com.sun.management.jmxremote.port` and `com.sun.management.jmxremote.rmi.port` independently, or perhaps if the build pack auto incremented `com.sun.management.jmxremote.rmi.port` for each app instance.  That way you could access multiple instances at the same time.  Ex:  instance #0 on 5000, #1 on 5001, etc...  

Thanks

**Comment by nebhale** [comment]
While the problem is undoubtedly real, I'm not sure why it is.  The JSR-160 and RMI ports [always match one another](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/framework/jmx.rb#L42-L43), so the tunnel for one should match the tunnel for the other.  I'm guessing something is doing an internal redirect causing the issue.

Outside of an easy fix, I think we'll update the docs to be more clear rather than making the implementation more robust.  Instance choice should be handled via the `cf ssh -i` argument, and I don't want to add anything additional if you can't use non-matching ports.  In the end, this is not something that should be used very often so putting a ton of engineering into it isn't in line with our goals.

I'll do some research about tunneling JSR-160/RMI over SSH, but be prepared for a doc-only change.

**Comment by jhliptak** [comment]
The blog at http://sykesm.mybluemix.net/posts/jmx-in-diego/ seems to document the issue in detail.

John Liptak
Principal Architect
Infrastructure Architecture & Strategy
931 14th St
Denver, CO 80202
John.Liptak@CenturyLink.com<mailto:John.Liptak@CenturyLink.com>
(303) 992-9623 (work)
(303) 437-4206 (cell)

All problems in computer science can be solved by another level of indirection" – Butler Lampson

**Comment by nebhale** [comment]
@jhliptak That's actually an issue that we've already solved.  We can make the connection just fine so long as port numbers all match.  It breaks down when the port numbers don't match.  So

```
$ cf ssh -N -T -L 5000:localhost:5000 <APP>
```
works, while 

```
$ cf ssh -N -T -L 6000:localhost:5000 <APP>
```

does not.

**Comment by dmikusa-pivotal** [comment]
Docs only change is fine with me.
