### ISSUE TITLE
Request for build of openjdk 1.7.0_80 and beyond

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#273]
I have a customer that is seeing an occasional ssl handshake issue with the java-buildpack build of openjdk 1.7.0_79.  They don't appear to have the same issue with Oracle build 1.7.0_80.  It appears that there was a potentially related bug [0] fixed in 1.7.0_80 and would like to see if an openjdk build of 80 also works for my customer.

On related note what are thoughts on continued support for Java 7 in the java-buildpack?  Sure, oracle has stopped publishing official builds of Java 7 but it appears that new releases continue to be pushed to openjdk.  Ubuntu appears to have continued releasing openjdk builds past u80 [1].  Should the java-buildpack follow suit?  I know my customers would love to continue receiving security and other fixes for Java 7 as they work to slowly move to Java 8 or 9.

[0] http://bugs.java.com/view_bug.do?bug_id=8052406
[1] http://packages.ubuntu.com/trusty/openjdk-7-jdk

**Comment by nebhale** [comment]
We've decided that we're going to follow [Oracle's advice](http://www.oracle.com/technetwork/java/javase/downloads/cpu-psu-explained-2331472.html) and stick with the CPU releases which is why we've got `_79` and not `_80`.  I'm not inclined to put the PSU releases into our repository, but I'm happy to work with you to get our dependency builder running so that you can add it to your internal repository.

We're also taking the position that we're not going to build JREs versions that don't have an Oracle-blessed equivalent.  On a technical level, it's nearly impossible to tell *which* tag we should build (I mean just look at [this list](http://hg.openjdk.java.net/jdk7u/jdk7u/tags)); we know from experience that the last `-b##` is not always the one that gets shipped.  Beyond that though, we're taking an opinionated stand that the if Oracle (the primary contributor) thinks that the 7 line has been EOL since Apr 2015, then we agree with that.  And again, we've made sure that our JRE builder is public and open source and are happy to help you get it running so you can create non-Oracle-equivalent builds for internal use.

**Comment by youngm** [comment]
Thanks @nebhale that all makes sense and is good information I was not aware of that I can relay to my customer.

I still believe that java-buildpack community blessed builds beyond the EOL would be a nice value add for all CF customers but I cannot complain too much since all it would do is save me the time and effort of setting up a dependency build environment of my own.

To help me decide if I want to start publishing my own builds are there other technical reasons, besides not knowing what tags to promote, you're aware of to avoid builds beyond the official Oracle releases?

**Comment by nebhale** [comment]
Nope, no technical reasons that I'm aware of.  I'm hoping that whomever is committing into those repos isn't changing the build system, and if that is true, then our builder should work against any tag.

**Comment by youngm** [comment]
@nebhale Thanks.
