### ISSUE TITLE
AppDynamics agent does not get downloaded

### ISSUE THREAD

**Issue by nkatre** [cloudfoundry/java-buildpack#288]
Hi,

With this buildpack, when you create a cups service for appdynamics or when you use the AppDynamics Service Broker tile, with an application, the appdynamics agent does not get downloaded.

Initially, this used to work but now its not working now

**Comment by nebhale** [comment]
@nkatre After extensive discussion AppDynamics has chosen not to extend a distribution agreement for their agent to the Cloud Foundry Foundation.  This means that we will no longer be able to enable the AppDynamics framework by default (we have a policy of disabling frameworks that will not work without user intervention).  The framework will continue to exist in the code base, in a disabled state that can be enabled with a single-character change in a buildpack fork or using an environment variable.

**Comment by nebhale** [comment]
In the earlier post, I misspoke.  Recently, our automated dependency gathering system was broken by an update to the AppDynamics SSO system.  We did not want to be in a situation where the buildpack was shipping outdated and insecure versions of the App Dynamics agent so we were confronted with the need to reverse engineer the new SSO system.  With distribution negotiations on going, I decided to disable the agent in `master` rather than make that investment immediately.

**Comment by nkatre** [comment]
Thanks for clarifying this.

**Comment by nkatre** [comment]
@nebhale Whats the env variable to enable the AppD service. Also can you mention the location of the file change within the buildpack were the AppD can be enabled (This is for the fork)

**Comment by nebhale** [comment]
It is the reversion of [this change](https://github.com/cloudfoundry/java-buildpack/commit/46826a0cc50169e03d8850276d57ecfe408d19d4), but adding a private internal repository that contains a legally acquired copy of the AppDynamics agent.
