### ISSUE TITLE
jrebel 6.4.2a prevents offline build

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry/java-buildpack#290]
Hi,

Jrebel 6.4.2a was released a few days ago and the buildpack is not happy about "2a":
$ bundle exec rake package OFFLINE=true
rake aborted!
Invalid micro version '2a'

Changing config/jrebel_agent.yml to 6.4.2 doesn't fix the issue. I managed to build the offline buildpack by removing the last line from build/staging/resources/cache/https%3A%2F%2Fdl.zeroturnaround.com%2Fjrebel%2Findex.yml.cached

**Comment by muthu-s** [comment]
I am facing the same issue since yesterday for Liberty build pack as well. can you confirm that removing the 6.4.2a line from cached yml is not a problem?

**Comment by nebhale** [comment]
The Zero turn around team have an invalid index file.  I'll both contact them to improve it and add a fix to the buildpack that will warn and ignore on illegal values.

**Comment by salhadef** [comment]
why not change /lib/java_buildpack/util/tokenized_version.rb valid_major_minor_or_micro to use \w instead of \d for people who want to use that new version of jrebel?

154       def valid_major_minor_or_micro(major_minor_or_micro)
155         major_minor_or_micro =~ /^[\w]*$/ || major_minor_or_micro =~ /^\+$/
156       end

**Comment by nebhale** [comment]
The version number is specified and documented [here](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md#version-syntax-and-ordering).  Changes to that would be a breaking change.  It's up to the repositories to meet the specification rather than the specification changing to meet the repositories.

**Comment by salhadef** [comment]
makes sense.  thx.

**Comment by samof76** [comment]
Any updates on this?

**Comment by nebhale** [comment]
I've not gotten a response from JRebel about fixing their repository, but the build in `master` is now more tolerant of the problem.

**Comment by mirkoadari** [comment]
Sorry this happened. We weren't aware of the restrictions on the version format. We'll update the repository as soon as possible and I'll let you know here as well.

@nebhale I tried to find your email, but weren't able. For future reference, so we can avoid communication black holes, how did you try to reach out?

**Comment by nebhale** [comment]
@mirkoadari I sent an email to Mark Taber which admittedly was a long shot.  Your best bet is to create an account on http://cloudfoundry.slack.com and find me in #java-buildpack.  If you want email, it's bhale@<Pivotal's Domain>.

**Comment by mirkoadari** [comment]
We've updated the repository. If there's any issues in the future, please shoot an email to support@zeroturnaround.com. That's the fastest way to get to a resolution. Sorry for trouble everyone.
