### ISSUE TITLE
Use tomcat configration files of external

### ISSUE THREAD

**Issue by jiheyangying** [cloudfoundry/java-buildpack#316]
hello, i try to push java app and run tomcat in my own conf-file ("server.xml" "logging.properties" "context.xml"). I use command "JBP_CONFIG_TOMCAT: "{ tomcat: { external_configuration_enabled: true }, external_configuration: { repository_root: \"http://repository...\" } }"" to set env.  My xml files is under the dir of application's "app.war/WEB-INF/", i try many "repository_root" to find conf-file (such as "/WEB-INFO/  or  \"),but failed. So can you tell my how to set "repository_root" to find my files?  thank you very much！

**Comment by violetagg** [comment]
Hi,

From the documentation [1] you have 

```
external_configuration.repository_root	The URL of the External Tomcat Configuration repository index
```

More information for the repositories can be found here [2]
Does your repository comply with the requirements for a Repository?

Best Regards,
Violeta Georgieva

[1] https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md
[2] https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md

**Comment by jiheyangying** [comment]
thank you for your answer, Do you mean i need to set repository like this?
app.war
     |__WEB-INFO
                |_____index.yml
                |_____server.xml
                |_____logging.properties
                |_____context.xml
and set index in index.yml, and then set  "repository_root"  to "/WEB-INFO/" ? 
But i have a new problem,that where is the root dir of "repository_root", I mean does  "/WEB-INFO/" is right ? thank you very much

**Comment by violetagg** [comment]
Hi,

Check again the links above:

```
The repository is an HTTP-accessible collection of files...
```

For example the repository may look like this:
```
/index.yml
/tomcat_configuration-1.0.0.tar.gz
```

And ```tomcat_configuration-1.0.0.tar.gz``` may look like this:
```
tomcat
|__conf
   |__context.xml
   |__server.xml
   |__web.xml
   |...
```

Regards,
Violeta

**Comment by jiheyangying** [comment]
Hi，
    Ah！i got it！thank you very much！
    But in this way, I have to set up a Apache Server to store my xml files. Is there any method to put the xml files in application(app.war) , and then make these xml files be effective? 
    I think that from user's point of view, "push" the xml files with applications together is more convenient.

Jiheyangying

**Comment by nebhale** [comment]
Configuring an external application server using an application is a poor separation of concerns and therefore is not supported.  The biggest problem is that you end up in a situation where your application will run differently on Cloud Foundry (which could read your application for configuration) and outside of Cloud Foundry (which could not read your application for configuration).  This leads to a hidden failure versus requiring externalized configuration which, while still possibly failing because of missing configuration, makes that externalization explicit.

If you want to configure your server on a per-application basis, you should be embedding the server using something like Spring Boot.
