### ISSUE TITLE
Default java version is chosen by alphabetical but not numerical order

### ISSUE THREAD

**Issue by Ekaterina001** [cloudfoundry/java-buildpack#324]
Please have a look at https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/index.yml
As I understand the default java version for now (if not setting environment variables) should be the last version:  1.8.0_101: https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_101.tar.gz
But for now it is actually: "Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz"

**Comment by nebhale** [comment]
Yeah, that's by design.  Since the qualifier can be text, it is lexically ordered.  The ordering is documented, as contract, [here](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md#version-syntax-and-ordering).  That addresses, _why_ it's behaving like that, but I'm not sure how we'll solve the result of it, that `_101` isn't being selected.

**Comment by sgrinev** [comment]
maybe change the contract? E.g. if it's a number sort numerically otherwise sort lexically?

**Comment by nebhale** [comment]
Adding that additional complexity to the algorithm makes it harder to reason about exactly what version will be selected.  I'm not totally against making that change, but since it'll be backwards incompatible, it'll necessitate a major version bump.  That's not a change that we'll make lightly.

**Comment by sc-moonlight** [comment]
Given that there was a 1.8.0_5, and that 1.7 included 8 single digit qualifiers, I unfortunately agree the lexical sort is a problem.  I'll also add that IMHO I think this an issue is really Oracle's fault for using a qualifier that is really a micro/patch part of the version.

**Comment by nebhale** [comment]
Well, given hindsight we could have gone with triple digits the whole way through (`_072`) but that wouldn't have matched the commonly known versions either. I need to investigate, but I'm thinking that we can do something like `1.8.0_1+` to solve the problem. I need to see how tightly we defined the wildcard contract for qualifiers.

**Comment by Ekaterina001** [comment]
@nebhale : Setting environment variable as 
cf set-env <APP_NAME> JBP_CONFIG_OPEN_JDK_JRE "{jre: { version: 1.8.0_1+ }}"
didn't work for me (restaging fails).
Only strict 1.8.0_102 works (or 1.8.0_+ that does not change anything).  Could you please help with correct syntax for this case.

**Comment by nebhale** [comment]
@Ekaterina001 Until the previous commit, this didn't work.  I've loosened the wildcarding behavior so it now behaves as an "ends with" style wildcard and updated all of the JRE configurations to `1.8.0_10+` (couldn't do `1.8.0_1+` because there's a `1.8.0_11` 🙍).  If you've got your auto-merge configured now, these should have flowed down to your fork directly.  Let me know if you're still seeing problems with it.

**Comment by Ekaterina001** [comment]
@nebhale : Now it works. Thank you!
