### ISSUE TITLE
Links to docs on Readme are broken.

### ISSUE THREAD

**Issue by zabawaba99** [cloudfoundry/java-buildpack#330]
All the links in the README point to a `cloudfoundry/docs` repository which doesn't seem to exist anymore so they all return `404`s when clicked.

**Comment by nebhale** [comment]
I'm not sure what links you're describing.  I'm looking at the [raw Markdown source](https://raw.githubusercontent.com/cloudfoundry/java-buildpack/master/README.md) and don't see any links to `cloudfoundry/docs` at all.

**Comment by scottfrederick** [comment]
I just noticed this also. All of the [Additional Documentation](https://github.com/cloudfoundry/java-buildpack#additional-documentation) links are broken, because the relative path into the repo files isn't correct. 

e.g. the link for `Design` is `https://github.com/cloudfoundry/docs/design.md`, but should be something like`https://github.com/cloudfoundry/java-buildpack/blob/master/docs/design.md`.

**Comment by nebhale** [comment]
Then this is a GitHub issue.  Those links haven't been changed since [June 21, 2013](https://github.com/cloudfoundry/java-buildpack/blame/master/README.md#L63).  Wonder where I open an issue for that...

**Comment by nebhale** [comment]
Hell, it's even [enshrined in the docs](https://help.github.com/articles/relative-links-in-readmes/).

**Comment by nebhale** [comment]
Fixed on GitHub's end.
