### ISSUE TITLE
 The admin user can not view the new organization

### ISSUE THREAD

**Issue by wybrono** [cloudfoundry/java-buildpack#342]
I created a new organization, and the authority of the organization manager attached to the admin user, but with the admin user login appsmanager, still can not see the organization. But with the cli operation, I can see the organization.
why?

**Comment by DanielJonesEB** [comment]
You need to also _associate_ the user with the org - setting a role isn't enough.

https://apidocs.cloudfoundry.org/245/organizations/associate_user_with_the_organization.html

I also got caught out by this when first working with the CloudController API, but it's part of the CC behaviour rather than that Java Buildpack.

**Comment by nebhale** [comment]
This is not a Java Buildpack issue.
