### ISSUE TITLE
appdynamics file in common conf directory not picked up

### ISSUE THREAD

**Issue by equick** [cloudfoundry/java-buildpack#349]
Hi,

I have tried adding `custom-activity-correlation.xml` to `resources/app_dynamics_agent/conf` in the mule buildpack but it does not override the copy at `resources/app_dynamics_agent/ver4.2.7.1/conf/custom-activity-correlation.xml`

The documentation implies this should be possible so just wondered if there is an environment variable I need to set in addition to pick up the version in the common location?

https://github.com/mulesoft-consulting/anypoint-buildpack/blob/master/docs/framework-app_dynamics_agent.md#Additional Resources

Thanks for any help.
Ed

**Comment by nebhale** [comment]
The `resources/` directory is an overlay on the component's sandbox.  So the file `resources/app_dynamics_agent/conf/custom-activity-correlation.xml` would be expected to show up in the droplet at `<APP-JBP-ROOT>/app_dynamics_agent/conf/custom-activity-correlation.xml`.  In order to see `<APP-JBP-ROOT>/app_dynamics_agent/ver4.2.7.1/conf/custom-activity-correlation.xml`, you'd need to place your file in `resources/app_dynamics_agent/ver4.2.7.1/conf/custom-activity-correlation.xml`.  I believe that this means that you'd be tied to AppDynamics 4.2.7.1 and would have to update the buildpack's `resources/` directory each time you used a new version of AppDynamics.
