### ISSUE TITLE
Support multiple JREs and allow selection by app

### ISSUE THREAD

**Issue by michele-mancioppi** [cloudfoundry/java-buildpack#356]
There are some hardships that come from the current JRE selection mechanism in the buildpack and I'd like to discuss possible solutions.

**Status Quo**

Changing the type of JRE supported by the buildpack is usually possible by setting a different repository via the manifest using the `JBP_CONFIG_OPEN_JDK_JRE` option. However, this requires adding a dependency to the repository in the manifest of all apps that want to use something that is not an OpenJDK. With JDKs like Oracle's or SAP's, this usually means that one prepares an "internal" repository somewhere which is likely specific to one deployment of Cloud Foundry. If your organization has many, unrelated Cloud Foundry deployments, developers start going *mad* about which JVM repo to use. Since different JVMs provide different options and features, all of a sudden apps lose functionalities or logs because they land on an OpenJDK that does not have some assumed, vendor-specific extensions.

(Even uglier with the manifest is overriding the content of the `component.yml` so that a different JVM is enabled, but that is obviously even worse than just overriding the JVM repo.)

Another option, that shifts the weight away from developers and, unfortunately, puts it to the operators of the landscape, is to fork the java buildpack, modifying the config to have by default the internal JVM repo. There madness ensues with the tracking of the java buildpack and rebasing the small repo-related change on it. And, in case the developers do not want to use the default JVM for whatever reason, the start overriding the repo again (double madness!).

I may be missing some option, but overall the process of selecting a JRE is not very streamlined.

**So what can we do?**

Ideally, the buildpack would come with all JREs "active" in the `component.yml` and a selection mechanism would be available via manifest and/or environment.

I played around with the scenario and came up with a [proof of concept](https://github.com/michele-mancioppi/java-buildpack/tree/multi-jre) (which is currently of alpha-quality) where the buildpack supports multiple JVMs (as long as they have a reachable repo) and which one to use is selected either via an environment variable (ideally it would be configurable as a manifest attribute like `name` but I have not gotten that to work yet :D) or the first JRE from the `components.yml`.

I am very much interested in gauging the interest in the community and feedback and pointers on the best way to implement the feature, should interest be there.

**Comment by nebhale** [comment]
The recommended way of dealing with using a non-standard JRE that is company-wide, is for the company to fork the buildpack and make the one-line change to use their own repository.  In fact this is not only supported, it's encouraged and [has it's own name, "expert mode"](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/buildpack-modes.md#expert-mode).

Once companies have decided to have their own internal repository for a single component (like a JRE), many find that they'd like to host the repositories for _all_ of their dependencies internally.  To this end, we make [tools for replicating our repository](https://github.com/cloudfoundry/java-buildpack-dependency-builder#replicating-repository) available.  This allows companies to include updated dependencies on a schedule that suits them.

The buildpack itself is designed such that supported changes using our documented API (configuration and component additions) will merge in without any conflicts.  We ensure that this holds true by maintaining [four downstream forks that incorporate upstream changes without human intervention](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack?groups=auto-merge).  We make the [tools for doing this available](https://github.com/cloudfoundry/java-buildpack/blob/master/ci/auto-merge.sh) as well and are happy to help people get started using them.

The general philosophy of the Java Buildpack is the JRE selection is below the value-line for application developers.  Allowing per-application selection of different varieties of JREs isn't a goal that we're interested in achieving. We do realize that often times, enterprises have rules about which JREs should be used for all applications and that's why we support the ability to select different options, for all users of a given buildpack.  We've done extensive work to allow operators to fork the buildpack and make this change, enabling them to enforce that all of their applications use the enterprise-decreed JRE.

**Comment by michele-mancioppi** [comment]
Thanks for the very comprehensive reply. I understand the rationale now. I still find it unfortunate that, given this stance, there may not be a way any time soon to develop some JVM-specific integrations outside of forking the buildpack and maintaining the fork. Hopefully this can be re-evaluated should there be more jREs available to the community with value-adding functionality.

**Comment by nebhale** [comment]
@michele-mancioppi This is why we aggressively court external contribution.  If you prove out a useful feature in your fork, or you find that our code doesn't allow you to do something in your fork (forcing you to extend in a non-supported way), we would love to hear about it.  Many of the integrations and API features that exist today started as forks that we've integrated upstream.
