### ISSUE TITLE
Springboot app with Groovy Bean DSL config fails to start, detection by multiple containers

### ISSUE THREAD

**Issue by raffian** [cloudfoundry/java-buildpack#360]
Springboot 1.4.2 Java/Maven project on JDK 1.8, 
cf version 6.22.2+a95e24c-2016-10-27

Project uses [Groovy beans DSL](http://docs.spring.io/spring-boot/docs/current/reference/html/cli-groovy-beans-dsl.html) for dependency injection:

`src/main/resources/META-INF/spring/gbeans.groovy`
```groovy
beans {    
    myDSLBean(route.processor.SimpleBean){
        name = "hello"
        count = 3       
    }
}
```
## Problem
Builds/runs without issue when standalone, but upon deployment to CF, error occurs due to multiple container detection by Java Main and Springboot CLI:
```
-----> Java Buildpack Version: b050954 | https://github.com/cloudfoundry/java-buildpack.git#b050954
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Application can be run by more than one container: Java Main, Spring Boot CLI>
Application can be run by more than one container: Java Main, Spring Boot CLI
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
```

Since the project satisfies detection criteria for Java Main and Springboot CLI, the error is not unwarranted. Having said that, I believe the criteria for Springboot CLI, specifically in regards to "if the application has one or more Groovy files", is too vague considering Springboot natively supports Groovy bean injection for Java-based projects, a feature gaining popularity over legacy XML-style bean config.

After reviewing the detection criteria, I was unable to tweak the project to ensure detection by only Java Main. Is there no other option that doesn't involve migrating back to XML bean config? 

## Question on Detection Criteria
Is detection criteria **all** or **none**? [SpringBoot CLI](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-spring_boot_cli.md) lists 5 criteria suffixed with "and"; does this mean all 5 criteria must be met, or just a single one? If single criteria is sufficient to satisfy detection, the documentation should be clear on that since the container - given how it's currently worded - appears to use boolean logic for the selection process. 

## Suggestion
The manifest should allow applications to "prefer" a startup container, regardless if detection criteria for other containers are satisfied; is something like this feasible?
```
---
applications:
- name: sbootdsl
  memory: 128M
  container: javamain
```

Runnable project here:
https://github.com/raffian/test/blob/master/springboot-groovyDSL.zip

**Comment by nebhale** [comment]
@raffian Before I even replicate the issue, I'm reasonably sure that you're doing everything right and running into this issue in a legitimate way.  We've not seen this before (or at least not seen anyone open an issue about it) as most people who are writing Spring Boot applications, are using [Java Config](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-java) rather than Groovy configuration.  So to answer your question about configuration without XML, yes there is an alternative, and it doesn't require putting Groovy on the classpath just for configuration.  Where we typically see Groovy configuration is with pure-Groovy Spring Boot applications.  That being said, this is a supported strategy for Boot and we should try to handle it.

The manifest isn't the right place to explicitly state a preference for a Java container as it is completely language (and buildpack) agnostic.  In essence, it sits at a lower level than the buildpack and doesn't know about the internals of any individual buildpack.

At this point your best bet is to use [Java Configuration](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-java) although you could also use [Environment Variable Buildpack Configuration](https://github.com/cloudfoundry/java-buildpack#configuration-and-extension) to disable the [Spring Boot CLI Container](https://github.com/cloudfoundry/java-buildpack/blob/834dffe704f25c29d3dd9b111b8cf0b66ef45257/config/components.yml#L25) until we've got a permanent fix in place.

**Comment by raffian** [comment]
Hi Ben,

Thanks for taking the time to review the issue. This problem _does_ have a little history here, although based on past issues, it's taken different forms; the principles, however, appear to remain the same. The suggestions you made look good, but probably better suited for future projects at this point; changing the services in question isn't practical because they're already developed.  Neverthless, we look forward to a permanent solution; any ETA on when that may be?

PS: Can you advise on the question regarding "all or none" detection rules?

**Comment by nebhale** [comment]
This isn't likely to get done before the move to Cloud Native Buildpacks.  We have addressed the issue there already though.
