### ISSUE TITLE
SSL validation error with custom root certificate

### ISSUE THREAD

**Issue by amirthraj** [cloudfoundry/java-buildpack#372]
To add custom cacert to the javabuildpack, i used to place it in resources/open_jdk_jre/lib/security/cacert
and that was working earlier until Java Buildpack 3.10. With the Java buildpack 3.12 it doesnt work anymore. I get "javax.net.ssl.SSLHandshakeException:"
How do i add a custom root certificate to the java buildpack?

**Comment by nebhale** [comment]
In 3.12, we enabled the [`ContainerCertificateTrustStore` framework](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_certificate_trust_store.md) by default.  This framework looks to the container's certificate store for CA's favoring those instead of the ones in the JRE. This is to support using BOSH/Ops Manager [Trusted Certificates](https://bosh.io/docs/trusted-certs.html) feature.

You have two options to get the same behavior as before, the first is to add your certificates via BOSH/Ops Manager which will get them picked up directly.  Second, since you already have a fork, you can disable the `ContainerCertificateTrustStore` by [commenting out the framework](https://github.com/cloudfoundry/java-buildpack/blob/master/config/components.yml#L41) in the frameworks list.

In the mean time, I'll update the `ContainerCertificateTrustStore` in order to combine both the container certificates and the JRE's certificates into one trust store with everything.
