### ISSUE TITLE
[Question] buildpack version 3.10 doesn't understand ${cloud.services.mysql.connection.username}

### ISSUE THREAD

**Issue by LeeU1911** [cloudfoundry/java-buildpack#379]
Hi all,

I've been researching this problem for a few days. I even compared code between buildpack v3.1 and v3.10 but due to not knowing ruby and lack of experience, I couldn't find out why every time my app is deployed with buildpack version 3.10, I've got an error saying `Access denied for user '${cloud.services.mysql.connection.username}'@'XXX.XXX.XXX.XXX' (using password: YES)`

When I deploy it with buildpack version 3.1 and lower spring boot version (to v1.3.X), everything's working well. If I upgrade spring boot version to 1.4.X and use buildpack v3.10, the app can't start because of error above. From the error, I assume it couldn't understand the externalized configuration in properties file. From [this article](https://spring.io/blog/2015/04/27/binding-to-data-services-with-spring-boot-in-cloud-foundry), it seems the buildpack translates Cloud Foundry VCAP_* environment variables into usable property sources in the Spring Environment so I guess for some reason in version 3.10, it doesn't do that anymore or the convention somehow changed.

Additional info: my app uses 2 datasources, so we follow configuration in spring boot documentation [like this](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-two-datasources) and don't use the standard spring.datasource configuration in properties file.

Any idea would be very appreciated.

Thank you,
Tom

**Comment by nebhale** [comment]
I don't believe that the issue is in the buildpack itself, as those properties are parsed by [Spring Boot itself](http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/api/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.html) without the help of the buildpack.  You should open an issue over [there](https://github.com/spring-projects/spring-boot/issues), and reference this one.

**Comment by nebhale** [comment]
We'll need to do some more investigation, but it's possible that the issue is that the format of those properties (provided by Spring Cloud Connectors) changed when we [upgraded the dependency](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/commit/b6e1ee7fdc1e43eb426b22d53f43fe9822ad5eb1#diff-600376dffeb79835ede4a0b285078036R45) 18 months ago.  Do you have access to properties that are similarly named, but don't match exactly?

**Comment by LeeU1911** [comment]
Thanks for your answer. I double-checked and the app could access:
`${cloud.services.mysql.connection.jdbcurl}`
but not
`${cloud.services.mysql.connection.username}`
`${cloud.services.mysql.connection.password}`

I think you're right that somehow these have been changed. Do you have any clue about how I can find that out? I've been searching in documentation and release notes of spring boot but still no findings. Probably I overlooked something...

**Comment by LeeU1911** [comment]
One additional note is I can see in some tutorials there are two types of properties available currently. One starts with `vcap.services` and one starts with `cloud.services`. I agree with you that the former is parsed by Spring Boot itself, but I'm not sure about the latter. Do you have any idea?

Thanks,
Vu

**Comment by LeeU1911** [comment]
Thank you very much, Ben! I switched to use the one starts with `vcap.services` and it's all fine now. Should have done that earlier. I will also go through the documentation of Spring Cloud Connectors to see what changed.

I really appreciate your help although this is not the correct place for my question.

Thanks again and all the best,
Vu
