### ISSUE TITLE
Profiling App startup in CF

### ISSUE THREAD

**Issue by Xhings** [cloudfoundry/java-buildpack#403]
Hi,
I have an application that crashes in production during the scaling phase of our zero downtime deployment. Now sometimes it takes the ops folks to restart the app instance manually after they have crashed multiple times and stay in crashed status. I have decided to profile the app startup to figure out whats going on. I can profile my app as a stand alone jar file in my local but have trouble starting up my app after enabling Yourkit profiler in CF. I did not find any startup issue on my local so want to try on CF now. Couple of questions:

1. Can I profile the startup of the app on CF as I could do in my local? 
2. I can't ssh an instance which is in any other state than Running, but then there are options like -XX:-HeapDumpOnOutOfMemoryError. Is it possible to retrieve a heap dump/ gc log from a crashed instance?

Regards,
Xhings

**Comment by nebhale** [comment]
1.  At the moment, we don't allow custom `javaagent` parameters on the YourKit integration, but we certainly could.  Given the [startup parameters](https://www.yourkit.com/docs/java/help/startup_options.jsp) would being able to set any of these address your issue of profiling the startup of an application?  I don't see anything about suspending startup the way you would with a debugger, so it might not be possible.
1.  Because of the way that containers work on Cloud Foundry, on crash of an application, the filesystem that the application was run against is immediately recycled.  Therefore, any attempt at extraction of a heap dump (which is likely to be larger than the filesystem can hold anyway) would be immediately removed and unavailable to you.  As part of a forthcoming release, we're adding a utility called `jvmkill` that dumps a histogram of the heap on exit.  This isn't as good as an actual heap dump, but we think it's a good tradeoff given the limitations of the containers.  You can test today by staging your application with `-b https://github.com/cloudfoundry/java-buildpack.git`.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
