### ISSUE TITLE
App fails to start when stack_threads option in open_jdk_jre.yml is removed

### ISSUE THREAD

**Issue by hafeezpk** [cloudfoundry/java-buildpack#416]
CF App is failing to start when the **stack_threads** option is removed in the **open_jdk_jre.yml** file. I was assuming that **stack_threads** is optional and passed in only the memory_sizes and memory_heuristics.

**Comment by nebhale** [comment]
What failure did you experience and what version of the buildpack?

**Comment by hafeezpk** [comment]
Buildpack is the latest from master. (**8f3c030**)

The change is available in my fork [](https://github.com/hafeezpk/java-buildpack/blob/master/config/open_jdk_jre.yml)

Error is this

`ERR Instance (index 0) failed to start accepting connections
"reason"=>"CRASHED", "exit_status"=>2, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1492699126}`

stack_threads removed in open_jdk_jre.yml file

`jre:
  version: 1.8.0_+
  repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"
jvmkill_agent:
  version: 1.+
  repository_root: "{default.repository.root}/jvmkill/{platform}/{architecture}"
memory_calculator:
  version: 3.+
  repository_root: "{default.repository.root}/memory-calculator/{platform}/{architecture}"
  memory_sizes:
    metaspace: 64m..
    stack: 512k..
  memory_heuristics:
    heap: 75
    metaspace: 10
    stack: 5
    native: 10`

**Comment by nebhale** [comment]
`master` and the shortly to be released 4.0 use a new version of the memory calculator for which that value is required.  The [buildpack documentation](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#memory) describes the new requirements and more information about the new algorithm can be found at the [memory calculator documentation](https://github.com/cloudfoundry/java-buildpack-memory-calculator)

**Comment by hafeezpk** [comment]
I'm unable to get -Xss to 512k with the below config.

jre:
  version: 1.8.0_+
  repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"
jvmkill_agent:
  version: 1.+
  repository_root: "{default.repository.root}/jvmkill/{platform}/{architecture}"
memory_calculator:
  version: 3.+
  repository_root: "{default.repository.root}/memory-calculator/{platform}/{architecture}"
  stack_threads: 100
  memory_sizes:
    metaspace: 64m..
    stack: 512k..
  memory_heuristics:
    heap: 75
    metaspace: 10
    stack: 5
    native: 10

The java command on my app start shows -Xss 1M
Is this an other issue or my understanding isn't correct.

**Comment by nebhale** [comment]
As the [documentation states](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/jre-open_jdk_jre.md#java-options), configuration of memory spaces is now done with the standard Java memory options.  So `cf set-env <APP> JAVA_OPTS '-Xss=512M'` would be how you change the stack size, not with YAML configuration.

In addition, you cannot eliminate _any_ of the memory configuration values.  Because some of those values are unconstrained, and others are very large when they are not set, all of them must have some bounded value in order for your JVM to limit its size to that of the container it runs in.  For example, if you do not set `-XX:MaxDirectMemorySize` to some value, it is unbounded and could take `100TB` of memory in your `1216M` container.  Clearly this is not something you want to happen so all values have _some_ bounded value, which you can override as necessary.

**Comment by hafeezpk** [comment]
cf set-env <APP> JAVA_OPTS '-Xss=512M' makes the app not to start.

**Comment by TimGerlach** [comment]
I guess that's a typo. What @nebhale wanted to suggest is using 512**k**:

```
cf set-env <APP> JAVA_OPTS '-Xss=512k'
```

**Comment by hafeezpk** [comment]
cf set-env <APP> JAVA_OPTS '-Xss=512k' makes the app not to start :)

**Comment by hafeezpk** [comment]
I guess changing other memory sizes (for example, ReservedCodeCacheSize) works well with JAVA_OPTS. Only the Xss remains unchanged with approaches described above. Clearly there are issues the way Xss is handled in the newly released buildpack.

**Comment by TimGerlach** [comment]
You're right, there's another typo. It has to be

```
cf set-env <APP> JAVA_OPTS  '-Xss349k'
```
`Xss` works without `=`.

However, your manifest syntax only valid for the Java Memory Calculator v2.X (Java Buildpack 3.x). If you're using Java Buildpack 4.X (current master) the manifest syntax is:

```yaml
env:
  JAVA_OPTS: -Xss349k
```

**Comment by hafeezpk** [comment]
That works. :)

Just a question, not sure if this is the right place to post the question but isn't the -XX:MaxDirectMemorySize=10M is too less to be a default setting ?

**Comment by glyn** [comment]
@hafeezpk This isn't the right place for such a question because others won't necessarily see the discussion and it's a reasonable question. Please see "Community" at the bottom of the README https://github.com/cloudfoundry/java-buildpack-memory-calculator. The slack channel is a good place to discuss this...

**Comment by nebhale** [comment]
@hafeezpk In practice, it's surprising how few applications and libraries actually use directly mapped memory.  Given that if we choose a larger value then we'd have to reserve the memory and it wouldn't be used by most applications we've decided to keep it small.  If you'd like to propose a change to a larger default value, please open an issue in GitHub and we'll start tracking interest there.

**Comment by nebhale** [comment]
Thanks @TimGerlach for sorting out my typos.
