### ISSUE TITLE
Add environment variable override to specify new relic cups service

### ISSUE THREAD

**Issue by esunder** [cloudfoundry/java-buildpack#421]
Currently in order to startup the new relic agent, an app must be bound to a service with 'newrelic' in the name. The buildpack then detects this service and extracts the license key from the credentials object.

I would like to propose the an environment variable override, specified via manifest.yml in order to specify the cups service that the newrelic agent should use. I have added this functionality in my own fork: 
https://github.com/esunder/java-buildpack/pull/1/files

Is this something that could be useful to others?

Thanks

**Comment by nebhale** [comment]
We're unlikely to merge this in since there is already a broad range of places that `newrelic` can exist.  Specifically, the use of tags, which can be set with the `-t` flag on `create-service` command.  While this doesn't exist on the `create-user-provided-service` command at this time, the fix should be to add it to the CLI for feature parity with the `create-service` command.

As a general rule, we do not treat user-provided services any different than managed services, so wouldn't include any change that would start doing that.  In addition, any change to service detection would need to be broadly implemented across all components, not just New Relic.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
