### ISSUE TITLE
Support for AspectJ runtime weaving

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/java-buildpack#473]
If the app contains an `aop.xml` and `aspectjweaver.jar` it seems reasonable to expect that the user wants to attach the weaver as an agent. The only tricky question to settle is where to look for `aop.xml`, taking into account that jar files can also bring their own. Maybe we should ignore the jar files and assume that the user will place her own `aop.xml` in an "obvious" place (in `META-INF` or `org/aspectj` or the corresponding locations inside `BOOT-INF/classes`).

We'd need an escape hatch to back out (e.g. if the user actually already wove the classes and the weaver is accidentally present, or just to test the difference between AspectJ and Spring AOP).

**Comment by nebhale** [comment]
Sounds good.  Is there documentation that lists all of the “obvious” places that `app.xml` might go?

**Comment by dsyer** [comment]
> Is there documentation that lists all of the “obvious” places that app.xml might go?

The [AspectJ documentation](https://eclipse.org/aspectj/doc/next/devguide/ltw-configuration.html) mainly talks about it being in `META-INF` (but it also supports `org.aspectj` and that's better for Spring Boot apps if they use the fat jar format). Spring Boot moves things around, so those are not always in the root of the archive, andmaybe other jar formats do something different (e.g. a standard WAR puts it in `WEB-INF/classes`).

**Comment by nebhale** [comment]
After consulting with @aclement it appears that the interesting files are

* META-INF/aop.xml
* BOOT-INF/classes/org/aspectj/aop.xml
* BOOT-INF/lib/aspectjweaver-*.jar

**Comment by nebhale** [comment]
Also worth adding `-Daj.weaving.loadersToSkip=sun.misc.Launcher\$AppClassLoader` to exclude the system classloader which isn't used for the application in a Boot application.

**Comment by aclement** [comment]
Per what I just slacked Ben, adding further info I learned after digging. The discussion above is true for pre boot 1.5.0. For 1.5.0 and above the `META-INF/aop.xml` from a project source folder will end up alongside the classes in `BOOT-INF/classes/META-INF/aop.xml`. (as discussed in this commit: https://github.com/spring-projects/spring-boot/commit/080ff49c8d75cba626d324cc3aff4fe3f1bda68f ). So that's where we should check and the lack of it being in the root means you won't need to set that property. So you may need to do different things depending on how many versions of boot you care about.
