### ISSUE TITLE
AppDynamics agent unable to communicate to controller - connection issue

### ISSUE THREAD

**Issue by brickpattern** [cloudfoundry/java-buildpack#475]
I have had my  SpringBoot app on Java buildpack 3.17 working with AppDynamics agent  on CF 1.6 with proper CUPS service association.

Im facing an issue with CF 1.10 (new environment), the **appdynamics communication to controller fails**.  I have tried both Java buildpack 3.17 (AppDynamics agent ver 4.2.1.8) and as well as the latest Java buildpack  4.3. In both cases, I see a appdynamics agent log showing an error. 

```
[AD Thread Pool-Global1] 03 Aug 2017 21:11:53,138  INFO ConfigurationChannel - Sending Registration request with: Application Name [_MyApp_], Tier Name [_Services_], Node Name [_MyNode_], Host Name [349fcb06-a8d8-4f63-7dad-bf489ca94db3] Node Unique Local ID [xxxxx], Version [Server Agent v4.2.1.8 GA #11326 rb3b8138e547e0d2dd1cee3f6b3ef9ab6e14fdf33 113-4.2.1.next-build]
[AD Thread Pool-Global1] 03 Aug 2017 21:11:53,335 ERROR ConfigurationChannel - Fatal transport error while connecting to URL [/controller/instance/0/applicationConfiguration]: java.net.SocketException: Connection reset
```

Few lines before i see appdynamics.ip.addresss having a container related IP address (ip assiged to CF subnets)

```
INFO ConfigurationChannel - Detected node meta info: [Name:ProcessID, Value:14, Name:appdynamics.ip.addresses, Value:10.254.0.10,Name:supportsDevMode, Value:true]
```

**Comment by nebhale** [comment]
There haven’t been any significant changes to the AppDynamics framework since [September 4, 2015](https://github.com/cloudfoundry/java-buildpack/commits/master/lib/java_buildpack/framework/app_dynamics_agent.rb) so I don’t believe the issue is in the buildpack.  The error message of `java.net.SocketException: Connection reset` seems to indicate that the connection was successfully made to the AppDynamics server, but then some network device between the two (or possibly the server itself) has chosen the terminate the network connection after two tenths of a second.  I’d confer with AppDynamics about what might be causing this.

**Comment by brickpattern** [comment]
This may be a side information - with the latest PCF version, it is an out of box solution for WILLITCONNECT.  hitting that  webpage and providing IP address of AppDynamics controller, I see a good connectivity.

**Comment by brickpattern** [comment]
during CF push, this is what i see java buildpack 4.3 attempting to do 
Downloading AppDynamics Agent 4.3.3_6 from **https://packages.appdynamics.com/java/4.3.3.6/AppServerAgent-4.3.3.6.zip** (found in cache)
Expanding AppDynamics Agent to .java-buildpack/app_dynamics_agent (0.4s)

**Comment by brickpattern** [comment]
leaving this ticket open, so i can update my findings any i gather from AppDynamics team.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
