### ISSUE TITLE
Offline Version + Introscope

### ISSUE THREAD

**Issue by chlamprecht** [cloudfoundry/java-buildpack#483]
Hi,

I'm trying to use introscope in an offline Package (our cf installation has no connection to the internet). But it looks like theres no introscope package included in the cache folder.
So it seems that the user provided service doesn't have an effect when used at an "cf push".

Any idea how to get introscope working?

**Comment by nebhale** [comment]
Introscope support was disabled until [`v4.4`](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.4) because there was no legal permission to distribute the Introscope agent.  Now that the CA team is hosting those binaries in public and has created a distribution license that allows us to do so, the offline buildpack contains them.

If you would like to use the Introscope agent before `v4.4`, then you’ll need to [host a repository](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md) that contains an index and the binaries as well as updating your buildpack to [point at that self-hosted repository](https://github.com/cloudfoundry/java-buildpack/blob/v4.3/config/introscope_agent.yml#L18).
