### ISSUE TITLE
Roadmap for Java 9

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/java-buildpack#495]
Now Java 9 is GA . Many applications and frameworks need serious effort to be made compatible. Is there some roadmap for Java 9 support?

I guess there will be multiple milestones
* JDK 9 available in buildpack
* all frameworks and extensions compatible
* JDK 9 as default

**Comment by rjain-pivotal** [comment]
Is there a timeline for Java 9 support in the Java Buildpack?

**Comment by nebhale** [comment]
There is no fixed timeline for this at the moment, because the Java 9 change is going to be so intrusive.  The only hard date that we have at the moment is that I intend to make Java 9 builds available starting some time this week.  I’ll make no guarantees about the rest of the buildpack working with them until that is out in the wild and I have a better idea of how problematic Java 9 is generally.

We will eventually make Java 9 the default version (with reversion to Java 8 via configuration), but given the uproar about compatibility with the new module system, something tells me that that date will be some time away.

This will definitely be a community effort as we all move forward, but I don’t intend to take the buildpack to the bleeding edge to ensure that we support Java 9 applications ASAP.  We’ll make diligent progress closing out reported issues as well as proactively testing typical applications against the buildpack, but I wouldn’t expect to be going to production with Java 9 immediately.

**Comment by nebhale** [comment]
Java 9 JRE available: https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/index.yml. No testing of the buildpack against it yet.

**Comment by nebhale** [comment]
I've just commit a change that updates everything that the buildpack does in order to be ready for Java 9 (as I've been able to find).  However, it turns out that almost nothing else is ready for Java 9.  Of our test applications, more or less only Java Main applications (e.g. Spring Boot) seem to run properly.  Tomcat uses endorsed dirs, Ratpack does illegal reflection, Spring Boot CLI requires `javax.sql.DataSource`.  Suffice to say, I don't think that the ecosystem is ready to go.

However, if you want to start trying things out and opening issues about specific failures in the buildpack, I'm ready to start receiving them.
