### ISSUE TITLE
Using redis session replication

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/java-buildpack#508]
Hi team:
  I bound redis service instance to app, but session replication is not work.My buildpack is latest verison 。this is my app env:
![image](https://user-images.githubusercontent.com/21106445/32084217-61ccfec0-bafa-11e7-9c3e-7195be656518.png)
 
this is my application code:
![image](https://user-images.githubusercontent.com/21106445/32084285-bf6dc7d0-bafa-11e7-90a5-08aea9b559cd.png)
this is console logs:
![image](https://user-images.githubusercontent.com/21106445/32084331-062e7570-bafb-11e7-8181-724a03dd708c.png)

**Comment by nebhale** [comment]
Does the staging indicate that Redis Session Replication has been configured?

**Comment by geekyzk** [comment]
@nebhale 
![image](https://user-images.githubusercontent.com/21106445/32137251-c390bd2c-bc4e-11e7-9291-05c879d5fb2a.png)
![image](https://user-images.githubusercontent.com/21106445/32137254-c90eeb7a-bc4e-11e7-9b3d-70a3b40155d6.png)
![image](https://user-images.githubusercontent.com/21106445/32137256-ce1cf36e-bc4e-11e7-8de4-a46b189c585d.png)

Not found configured in staging.
I using pcf-dev to test in home.

**Comment by nebhale** [comment]
I see no indication that Redis Session replication is being configured automatically.  Please note that this feature is only for [WAR artifacts run with Tomcat](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#session-replication).  If I had to guess, you’re pushing an Spring Boot executable JAR which will not have this auto-configured.  You’re encouraged to use [Spring Session](https://projects.spring.io/spring-session/) and [Spring Cloud Connectors](https://cloud.spring.io/spring-cloud-connectors/) in order to configure Redis Session replication for Spring Boot applications.

**Comment by geekyzk** [comment]
Succuess!!
![image](https://user-images.githubusercontent.com/21106445/32211137-2415762a-be4c-11e7-8c22-c46e7c6391fd.png)
Session is store in redis
 But When i using  muilt instance to test.
![image](https://user-images.githubusercontent.com/21106445/32211204-6f50f0d8-be4c-11e7-945d-604002dfe344.png)
![image](https://user-images.githubusercontent.com/21106445/32211217-765745a8-be4c-11e7-9e2b-e6beaadcc930.png)
This application  session is not share.
My demo code is:
![image](https://user-images.githubusercontent.com/21106445/32211262-af414396-be4c-11e7-803e-cb9bcc44ce13.png)
It is a simple spring mvc demo.
 I looked @nebhale [session-application](https://github.com/nebhale/cfsummit-2014/tree/master/session-application)  project

**Comment by nebhale** [comment]
Great. I’m glad it worked it for you.
