### ISSUE TITLE
Class count factor findings

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack#510]
I've moved several of my orgs applications over to jbp4.  Several of those applications have needed a custom `MaxMetaspaceSize` set.  I've noticed that typically the larger the application the more likely the application will spill over the detected `MaxMetaspaceSize`.  It also seems that the smaller the application the more unused overhead available in `MaxMetaspaceSize`.

I don't know what experimentation went on to discover the current `0.35` factor.  I suspect that perhaps what is going on is the jdk provides an initial large sum of unused classes.  The more user provided classes the application provides the more significant the actual class count becomes?

A couple of thoughts:
* Perhaps the initial `0.35` factor could benefit from a bit more of a curve.  A smaller factor for smaller applications and a larger factor for larger applications.
* Perhaps we could exclude jdk classes from the class count and instead use a fixed typical jdk class count number and then determine a new factor for user provided classes.
* Perhaps we decide the current method is as good as it gets even though it has some flaws.  In this case perhaps the `0.35` factor could be exposed as a configurable value so that organizations can balance the risk of wasting memory vs default user experience themselves.  In my case I would probably make this factor a little larger since most of my orgs applications are larger and we would prefer a better default experience.

Thoughts?

**Comment by nebhale** [comment]
I'm inclined to change the number for everyone as it's the simplest to reason about.  Can you give me an idea of what the calculated metaspaces were and what you ended up changing them to?  Trying to get an idea of the difference in the amount of memory consumed.

**Comment by youngm** [comment]
Sounds good.  Data is more useful than assumptions.  I'll give you the data as I discover it.  I've only got one with solid data at this point.  I'll try to feed more into the issue as I get it.

APP_1:  This problem didn't expose itself till it hit production.
  JBP calculated loaded classes parameter passed into memory_calculator: -loadedClasses=29899
  JBP Calculated MaxMetaspaceSize: 183021K
  Customer was panicking so we set the MaxMetaspaceSize in production to: -XX:MaxMetaspaceSize=320m
  Number of classes loaded in production based on NMT data: 34932
  Size of committed Metaspace in production based on NMT data: 229796KB

**Comment by youngm** [comment]
LARGE_APP_1_NON_PROD: Same app but in lower lane without all functions exercised
* Number of classed loaded base on NMT data: 21905
* Size of committed Metaspace base on NMT data: 130634KB
* Everything else obviously the same.

**Comment by nebhale** [comment]
@glyn Any thoughts on this change?  I've not seen a lot of reports of the need to modify `MaxMetaspace` at the moment, but I am wondering specifically about

> Perhaps we could exclude jdk classes from the class count and instead use a fixed typical jdk class count number and then determine a new factor for user provided classes.

since I'm going to have to fake it for Java 9 (no way to examine the inside of the standard modules from a JRE installation).

**Comment by glyn** [comment]
@nebhale Here are my thoughts:
* No single value of the class count factor is going to satisfy all applications. Some will have insufficient memory; others will waste memory.
* It's worse to have insufficient memory than to waste memory, so we _could_ bump up the factor(s).
* We should consider exposing the factors to make them configurable so that people who want to tune the values can do so without forking the buildpack and/or memory calculator. That should probably be combined with bumping up the factor(s) because:
    * It's worse to have to tune the values than to waste memory.
    * It's worse to have insufficient memory than to have to tune the values.
* On using a fixed _typical_ JDK class count number, we cannot know for sure what is typical. The classes loaded from the JDK depend on the usage in the application. I'm loath to introduce yet another estimated value into the calculations.

**Comment by nebhale** [comment]
@youngm We expose the [`class_count` configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/config/open_jdk_jre.yml#L28) for this, which [bypasses the multiplier completely](https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/jre/open_jdk_like_memory_calculator.rb#L89).  Would setting that value directly (rather than us guessing at it) have solved this issue for you?  It seems like the calculation of number of loaded classes to memory usage is OK (maybe a bit high, but I'd rather be wrong in that direction) but we're just not guessing the number of classes you need.

**Comment by youngm** [comment]
@nebhale Obviously this can be worked around by apps having problems specifying their class count.  My concern is that I've seen a trend where applications with more classes are running more hot or out of metaspace more often than small applications and thought if there is a trend and not random then perhaps there is something the memory calculator could do to help.

That said, I haven't been overwhelmed with issues related to this.  I realize that any adjustment to this calculation would probably take data.  Since I don't have time to gather that data currently I'm fine closing this for now.

If in the future it becomes a bigger problem, I can create a new issue and we can figure out what kind and how much data you'd like me to gather to confirm what I'm seeing and possibly figure out how to adjust the calculation accordingly.  Sound good?

**Comment by nebhale** [comment]
Sounds good.  We did actually adjust it up once from 0.33 to 0.35 so it’s not unprecedented to make a chance.  In addition, the sizes we’re talking about are small enough (and proportionally affect larger applications more) that another adjustment up isn’t out of the question if this becomes systemic.  Let me know if you see an additional need.
