### ISSUE TITLE
Mutual TLS

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry/java-buildpack#516]
Hi,

I need a bit of clarity in regards to running Java apps that require mtls. Would there be any issue with pushing a Java app along with the keystore and truststore configuration to CF and having the application handle the client cert checks? 

I can see there is a certain property available in the 0.160.0 version of the routing release (and cf 275) that allow for the client cert to be forwarded to the app, but I also see similar discussions here (issue #378) prior to that release. Would the use case be possible with versions before 275? 

Thank you in advance.

**Comment by nebhale** [comment]
There is no problem with you pushing your own `KeyStore` and `TrustStore`.  The `SecurityProvider` that we contribute acts with a Decorator pattern [delegating](https://github.com/cloudfoundry/java-buildpack-security-provider/blob/master/src/main/java/org/cloudfoundry/security/DelegatingX509ExtendedKeyManager.java#L39) first to the [system `Key/TrustStore`](https://github.com/cloudfoundry/java-buildpack-security-provider/blob/master/src/main/java/org/cloudfoundry/security/CloudFoundryContainerKeyManagerFactory.java#L77) (e.g. your contributed and configured artifacts) and then to the [container `Key/TrustStore`](https://github.com/cloudfoundry/java-buildpack-security-provider/blob/master/src/main/java/org/cloudfoundry/security/CloudFoundryContainerKeyManagerFactory.java#L82).

The `X-Forwarded-Client-Cert` header is only contributed by the Router in recent releases, and even then only when configured to do so.  This was added specifically to support mTLS through the router, which therefore isn’t available before this router release.

**Comment by nebhale** [comment]
Oh that's absolutely the case the case that termination at any point other than the application itself causes issues, but not because we're overriding your `Key/TrustStore`.  At issue is that the application never sees the client's certificate since TLS is terminated elsewhere.  You can use container-to-container networking to ensure that termination is done at the application so that it has access, or update to the version of the router that does termination and then passes the certificate along with the `X-Forwarded-Client-Cert` header.

**Comment by cfmagnum** [comment]
Thanks for the clarification. I noticed you have published a mtls-sample on github which showcases the feature, however there seems to be an issue, even though both applications get to the running state successfully.

The client app's logs show this repeating error:

 ```
  2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT 2017-11-12 12:03:13.053 ERROR 7 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.SerialNumberExtractor.getSerialNumber(SerialNumberExtractor.java:48) ~[classes/:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.ClientApplication$Client.test(ClientApplication.java:67) ~[classes/:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[na:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```
Do you know what could be causing this? Thanks again.

**Comment by georgibarzev** [comment]
Thanks for the clarification. I noticed you have published a mtls-sample on github which showcases the feature, however there seems to be an issue, even though both applications get to the running state successfully.

The client app's logs show this repeating error:

 ```
  2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT 2017-11-12 12:03:13.053 ERROR 7 --- [pool-1-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.SerialNumberExtractor.getSerialNumber(SerialNumberExtractor.java:48) ~[classes/:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at io.pivotal.mtlssample.client.ClientApplication$Client.test(ClientApplication.java:67) ~[classes/:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[na:na]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
   2017-11-12T07:03:13.05-0500 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```
Do you know what could be causing this? Thanks again.

**Comment by nebhale** [comment]
That `mtls-sample` application only works in very specific scenarios at the moment unfortunately.  It needs to run in systems where the router is both doing the TLS termination, and has been configured to forward the client certificate.  Most CF installations, including Pivotal Web Services, aren’t configured like this unfortunately.  We’re in the process of changing PWS’ configuration so that this demo runs out of the box there, but it’s not ready yet.  The demo does run on PCF instances that have been configured this way though, which is when we use it.  If you’re a PCF customer who’s interested in seeing the demo run properly, I can give you some tips on how to configure your installation.

**Comment by georgibarzev** [comment]
I'm using a CF 276 installation that has the router doing the TLS termination and tried forwarding the certificate with either `router.forwarded_client_cert: always_forward` and `router.forwarded_client_cert: sanitize_set`. However the issue above is present when you check the logs for the client app.

The apps are set with environment variables as described, the client guid and the server url replacing the placeholder values:
```
cf set-env mtls-sample-server MTLS.ADMIN-CLIENT-IDS CLIENT_GUID
cf set-env mtls-sample-client MTLS.SERVER-ROUTE SERVER_ROUTE
```

**Comment by nebhale** [comment]
Ah, so noticed that the NPE is on the [client side](https://github.com/nebhale/mtls-sample/blob/master/client/src/main/java/io/pivotal/mtlssample/client/SerialNumberExtractor.java#L48) (the demo was always supposed to be for me in controlled circumstances, guess now that people are finding it, I should make it a bit more serviceable in these cases).  This would imply that there's no client-side certificate being presented.  Are you sure that the container that the application is running in has container identity?  The easiest way to tell is to see if there are `$CF_INSTANCE_CERT` and `$CF_INSTANCE_KEY` environment variables set.  You should also see log messages at `INFO` stating that a `KeyStore` has been created from the locations specified in those environment variables.

**Comment by georgibarzev** [comment]
I have not set those environment variables. Are the apps dependent on providing certs and paths to them via the environment variables?

I can already see access denied on the server app when trying to visit it on the browser without providing certs. I assume the positive outcome would be visible when the client app authenticates successfully, but I've not provided any certs to the apps in your repo. I suspect that getting past the access denied is also possible if I setup my browser to send client certs to the server?

What I'm looking to understand is if the client certificates would indeed reach the server application for mtls to be performed like in the use case I had in my earlier comments (Java app with keystore/truststore config) and if there is any dependency on any environment variables being set on the client and server apps.

**Comment by nebhale** [comment]
Those environment variables are how Diego exposes the artifacts for container identity.  If you're using your own identity (e.g. using `-Djavax.net.ssl.KeyStore`, etc.) then the sample application isn't currently setup to work at all for you.  The big issue is that when we look to extract the client side certificate serial number, we're looking [specifically for Diego's identity](https://github.com/nebhale/mtls-sample/blob/master/client/src/main/java/io/pivotal/mtlssample/client/SerialNumberExtractor.java#L34).  Give me a couple of minutes to update the sample to be more tolerant of the case where you're using user-provided identity and I think that might be enough to work for you.

**Comment by georgibarzev** [comment]
Is there some configuration (are the env vars above system or user provided and what is their value?) that needs to be done when I'm not providing the identity? 

And is the DNS change that the app domain is pointing to a router instead of the load balancer required for mTLS in general or just those examples? The load balancer is in pass-through mode.

Thanks again.

**Comment by nebhale** [comment]
When Diego is providing container identity, it uses those `CF_INSTANCE_{CERT,KEY}` environment variables to tell applications where to find the identity artifacts.  If your application provides it's own TLS certificate and private key (configured using `-Djavax.net.ssl.KeyStore` and its other related properties), then the Diego-specific configuration is irrelevant.

The goal of configuring DNS to point at the router instead of a load balancer is to get the router to terminate TLS and therefore have access to the client certificate to pass along to the applications.  If your load balancer is configured **to pass through encrypted TLS traffic without terminating it** then you should be fine.  If it is not configured to do that, you must bypass and route traffic directly to the router so it can do TLS termination.

The root issue you likely were seeing was that the sample application expects that the client certificate _is always Diego's identity certificate_.  This is a shortcoming of the sample application (there's no reason it can't work with any mTLS client certificate).  I've [updated](https://github.com/nebhale/mtls-sample/commit/c9c2b3f5344b07b17ba548fcdcb82b76004b2fcf) the sample to handle non-Diego client certificates and to output a useful error message if the problem is that there are _no_ client certificates.  Give it a go now and see if you get better results.

**Comment by georgibarzev** [comment]
I'm getting the same error again unfortunately.

Would those changes mean that I can setup a client keystore that will be forwarded to the server app? And is the server going to require any changes to trust that cert?

**Comment by lordcf** [comment]
Hi Ben thanks for quick responses, We using same app from your git repo(https://github.com/nebhale/mtls-sample). In that case, what we need to set  in  Identity variables `CF_INSTANCE_{CERT,KEY}`  are those created via app itself? If  no how we can create them for testing purpose and in this manual case how server going to cross-check them, Do we need to add some part of cert in Server app too.

**Comment by nebhale** [comment]
@georgibarzev What error are you getting exactly?  There is no longer an NPE possible, so if you're getting an error, it's something else.  I suspect you're getting one that says that there's no client certificate configured, which describes what the problem is.  You've **always** been able to setup a client keystore, nothing about that has changed.  The big difference is in later versions of CF is that Diego will now set one up for you (if you've properly configured it) so that you _don't_ have to provide your own.

**Comment by nebhale** [comment]
@lordcf and @georgibarzev It's probably worthwhile for you to review the [Diego documentation for this feature](https://github.com/cloudfoundry/diego-release/blob/develop/docs/instance-identity.md).

**Comment by rahul221192** [comment]
@nebhale We are still not added diego instance identity feature.Are there manual steps  by which we can add certs in this apps and verify that mtls is working  between client or server or not.
If yes can you please help in the steps that we need to follow.
How and where we need to add the certs?
and how to verify them?Or if there is sample example?

**Comment by georgibarzev** [comment]
Thanks for that clarification. The issue now is indeed the 'no client certificate' present in your latest commit, probably checked older logs by mistake yesterday. 

My concern wasn't necessarily about the client identity, but more about it reaching the server side via the router forwarding, which is the new feature I was looking into. Regardless of whether the identity is provided by the developer or automated by Diego. I assume your apps were intended to test the router forwarding AND the Diego-provided identity features together.

To simplify my question, assuming I am pushing a mtls Java keystore/truststore app, would I also need to refer to the keystore/truststore files with an environment variable?

Thank you in advance.

**Comment by nebhale** [comment]
You are correct, the sample application was developed to test the complete end-to-end connection of both Diego identity and router client-certificate forwarding.  Before that latest commit, we specifically attempted to extract the serial number of the Diego identity client certificate which would cause an issue if any other client identity was used.  Now that the change is in, _any_ client identity, Diego-provided or otherwise can be tested so the sample application will be a useful test for you and non-Diego-provided identity.

If you are contributing your own client identity, you **do not** need to reference those artifacts via `CF_INSTANCE_{CERT,KEY}`.  Instead, you should use the standard Java system properties to configure them.  This means that you will create a Java `KeyStore`, including it in your application (typically in `META-INF/` so that it can't be served by accident), and referring to it via [`-Djavax.net.ssl.keyStore` and its related properties](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#CustomizingStores).  The sample application now communicates to you, via the more descriptive error message, if you've configured your client identity properly.

**Comment by georgibarzev** [comment]
I assume adding my own identity on the client, would require providing a server truststore as well to authenticate the client?

**Comment by nebhale** [comment]
Correct.  Typically that is done by adding the certificate to BOSH's trusted certs which the router will use for it's trust store.

**Comment by georgibarzev** [comment]
Would it be possible to provide app specific truststore config when pushing the server code?

**Comment by nebhale** [comment]
In detail, the way this works is that TLS is terminated at the router including **trust** of the client certificate.  The client certificate is either trusted or not, but the contents of the client certificate are never inspected.  If the client certificate is **trusted**, it is encoded in the `X-Forwarded-Client-Cert`, and a non-secure (i.e. HTTP) connection is made to the container and the application in the container.  There is then a [servlet filter](https://github.com/cloudfoundry/java-buildpack-client-certificate-mapper/blob/master/src/main/java/org/cloudfoundry/router/ClientCertificateMapper.java#L44) that extracts the certificate from the `X-Forwarded-Client-Cert` header and puts them into the `ServletRequest` in the standard location _as if the container had terminated TLS, even though it has not_.  At that point, standard Java security frameworks (e.g. Spring Security) operate on the artifacts they expect (e.g. the `Certificate`) for authorization.  Note, that since the request came in via HTTP and **not HTTPS**, the certificate is never "trusted"; the router establishes trust and the application then assumes trust and inspects the contents of the certificate (e.g. `CN`) for authorization.  Therefore, validating trust on the server is unnecessary.  If you wanted to validate trust again (even through it's already been validated by the router in order to have gotten the request in the first place), you can include a trust store in your application using `-Djavax.net.ssl.TrustStore` and it's related properties.

**Comment by georgibarzev** [comment]
Thanks, that was very useful. 

Sounds like if you want a server app implementing it's own specific keystore/truststore rules that are not shared on the router/with the rest of the apps, you can include that in your source code and expect the router forwarding to provide the certificate for a second authorization at the app itself, which might reject it based on its keystore/truststore setup.

**Comment by nebhale** [comment]
Correct.  But the key to remember that **authorization** (i.e. given a known user, should that user be allowed to access) is a separate question to certificate trust (which is really **authentication**) in mTLS.  There's no problem with a broad trust policy for certificates; in other words, do I trust that the contents of this certificate were signed by a trustworthy CA?  This is because **authorization** is done based on the contents of the certificate rather than the trust of the certificate.  So trusting every (reasonable) certificate doesn't gain any caller access to a system.  It just puts the application in the scenario that they can trust that the contents of the certificate (e.g. the `CN`) is a trustworthy piece of data to make authentication decisions based on.

This ends up being confusing because so often, mTLS **authorization** is done based solely on certificate trust.  This is analogous to their only being a single username/password that can authenticate into a system; if there's only one user, it must always be authorized.  Trusting a broad range of certificates is analogous to having many usernames/passwords that can authenticate, but then given an authenticated username, only some users have **authorization** to access the system.

**Comment by georgibarzev** [comment]
Is the platform certificate trust configured here: https://docs.cloudfoundry.org/running/trusted-system-certificates.html?

**Comment by nebhale** [comment]
Yep the second one.  I misspoke before as I deal with PivotalCF most of the time and we glue all those things together (including making sure that Diego places the router’s certificate in containers so callers will trust the router) under a single Trusted Certificates configuration.

**Comment by georgibarzev** [comment]
Thanks. Your last few comments were very useful and some of those details haven't been documented so clearly otherwise. 

A slight concert with the platform setting though - would it force the router to ask for certs on apps that don't actually require mTLS on the same platform?

**Comment by nebhale** [comment]
The request mTLS client certificates can take three forms, the server can

* not ask for a client certificate
* require a client certificate to be presented
* ask for a client certificate to be presented if available

The router is configured for item three.  It does not require a certificate, but if the client has one, it can be presented.

**Comment by georgibarzev** [comment]
Are those configurable options on the gorouter? I don't think I see the field for it there. Options 1 and 3 don't seem strict enough to actually force mTLS when required.

**Comment by nebhale** [comment]
The configuration is whether or not the router does TLS termination.  When it is configured to do termination, it does it via option three: asking for a client certificate if one is available.  If no client certificate is presented, then none is passed on to the application and since there was no authentication, no authorization can happen at the application layer.  This covers both the situations where an application does need mTLS and another does not.

**Comment by georgibarzev** [comment]
Hi Ben, would there be any method of always requiring the client cert to be checked against the ca_cert provided to the router? Thanks.

**Comment by nebhale** [comment]
I don’t believe so, but you can request such a feature from the router team.  I don’t think it’s a good idea for such a feature though, as it would affect _every_ host managed by the router.  This is pretty drastic for things like the AppsManager console, and other applications that are trivial enough that they don’t require client authentication in order to function.  It’s a much cleaner separation between applications for the router to request a client certificate if it exists, and for the application itself to validate that a required certificate was provided and that the identity within it is authorized.  This way, each application is free to decide if they need client certificate authentication and authorization.  I don’t see an issue with the router passing a request to the application without a required certificate as the application would reject the request as soon as it received it.

**Comment by georgibarzev** [comment]
It sounds like the routing team has actually been working on it, but it's not been released yet:
https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L76

I was only wondering if haproxy or another load balancer might potentially be able to achieve this.

I do agree about it potentially affecting the console and service broker apps as well though. It does look like the best and most straightforward option as of right now is for the app to check the XFCC header and reject if no certificate, assuming the router is not forwarding certificates when they weren't signed by the CA given to the router.

**Comment by nebhale** [comment]
Good to hear that they're working on it.

**Comment by nebhale** [comment]
I'm going to call this thread complete.  Feel free to contact us in the #java-buildpack CF Slack channel if you've got more questions.
