### ISSUE TITLE
[question] generating java buildpacks from modules using jdeps and jlink

### ISSUE THREAD

**Issue by jbuchberger** [cloudfoundry/java-buildpack#519]
Starting with **Java 9**, its tools `jdeps` and `jlink` enable customized java runtimes containing only the modules really needed, thus _allowing for much smaller images_. See also evaluations along these lines [here](https://blog.jdriven.com/2017/11/modular-java-9-runtime-docker-alpine/) and [here](https://jaxenter.de/java-9-tutorial-jlink-59103) (sorry, the latter article is only in german, you could try [googletranslate](https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fjaxenter.de%2Fjava-9-tutorial-jlink-59103&edit-text=&act=url), though).

So, do you think something similar to [this](https://bugs.openjdk.java.net/browse/JDK-8190738) is also achievable for or combineable with buildpacks or with the help of multi-buildpacks? See also another more detailed issue [here](https://bugs.openjdk.java.net/browse/JDK-8190739).

Cheers
Jörg

p.s. if you think this question is off-topic, please, be so kind to point me to another more suitable location if you happen to know thereof

**Comment by nebhale** [comment]
To be honest, we haven't really thought about this at all.  To date, droplets are much more governed by the size of their applications than they are by their JVM and other buildpack-contributed bits.  For example, when we push our [Java Main test application (i.e. Spring Boot)](https://github.com/cloudfoundry/java-test-applications) the output is as follows:

```
Downloaded app package (23.5M)
...
Uploaded droplet (69.7M)
```

For this trivial application, the overhead contributed by the buildpack is 46.2M.  The key here is that regardless of the size of the application, this value is the same.  So if you upload something larger than a trivial 20M application, that percentage shrinks towards not mattering very much at all.

We know that [our JRE](https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_152.tar.gz) is ~45M of that (it's been creeping up over the years)

![screen shot 2017-11-09 at 10 34 43](https://user-images.githubusercontent.com/60754/32623009-a8a01bcc-c539-11e7-96aa-339e9ca7d068.png)

and standard Java 9 is smaller already, so if there is savings to be had it's a good candidate.  We'd probably pursue savings, not so much by allowing each application to drop bits and pieces of the JRE, but rather by removing certain features (e.g. AWT, Swing) from our JREs and pass those savings along to all users.  That being said, as this is fixed overhead which shrinks as a percentage as application size increases, it's not tops on our list of things to look at.

If you think that there are obvious optimizations we can do for the JRE, I encourage you to submit PR's against the [JRE builder](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/openjdk9.sh) itself so that we can improve things for all applications on CF.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
