### ISSUE TITLE
non-unicode font support

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/java-buildpack#548]
Hi Team,

Do we support non-unicode font in java app?

An java app generates an BMP image which contains some Chinese characters. The image looks good when run in local computer, for example macbook. However the Chinese characters won’t be generated when run this app in PCF.

I have set `JAVA_OPTS '-Duser.language=zh_TW -Duser.country=TW'` however the Chinese character won't display properly. Is there any settings I missed?

Run in mackbook
`DavidZhou:Downloads dzhou$ java -jar image.jar 
BMP file generated: /Users/dzhou/D53.bmp
^C
DavidZhou:Downloads dzhou$`

Run in PCF
`ubuntu@bosh-stemcell:~$ cf push image-test -p image.jar -b java_buildpack_offline -f manifest.yml`
`ubuntu@bosh-stemcell:~$ cf set-env image-test JAVA_OPTS '-Duser.language=zh_TW -Duser.country=TW'`
`ubuntu@bosh-stemcell:~$ cf restage image-test`

Generated image file in Mac
![d53_mac](https://user-images.githubusercontent.com/17395452/35670581-e7f3ceaa-0773-11e8-9625-d5d8ff1322d9.jpg)

Generated image file in Mac
![d53_20180125](https://user-images.githubusercontent.com/17395452/35670580-e7c40cc4-0773-11e8-9d35-dc5e53212b82.jpg)

**Comment by David-Pivotal** [comment]
Hi Team,

Any advice is welcomed!

**Comment by jbayer** [comment]
hmm...i don't know the answer off-hand, but perhaps you might get a more responsive answer on stack overflow for the requirements for generating these characters on linux. the bosh stemcells (ubuntu 14.04 LTS with xenial kernel) have minimal packages installed, and similar goes for the ubuntu rootfs container base image https://github.com/cloudfoundry/cflinuxfs2

**Comment by David-Pivotal** [comment]
@jbayer Thanks for your comments. Really appreciate your help!

**Comment by David-Pivotal** [comment]
@nebhale Could you help advice on this issue?
I talked [this issue with cflinuxfs2 team](https://github.com/cloudfoundry/cflinuxfs2/issues/46) and Dave Goddard suggested it was better to be handled by java buildpack team.

**Comment by nebhale** [comment]
I'm not precisely sure what the issue is here.  I just pushed an application to PWS with no modification to the JAVA_OPTS:

```java
@RestController
@SpringBootApplication
public class EncodingTestApplication {

    public static void main(String[] args) {
        SpringApplication.run(EncodingTestApplication.class, args);
    }

    @GetMapping("/test")
    String test() {
        String message = "가다 こんにちは";

        System.out.println(message);
        return message;
    }

}
```

The outputs were:

```plain
$: curl https://ben-test-application.cfapps.io/test
가다 こんにちは
```

and from the application itself:

```plain
2018-02-12T10:11:36.27-0800 [APP/PROC/WEB/0] OUT 가다 こんにちは
```

That appears to indicate that the JVM is working as expected without any additional configuration.  If you don't believe that this test accurately represents your problem, please give me a test case that I can use to reproduce it.

**Comment by scottgai** [comment]
[issue548.zip](https://github.com/cloudfoundry/java-buildpack/files/1730602/issue548.zip)
@nebhale 
thanks for the update. 
since David is in PTO I'm attaching `image.jar` and manifest file here which customer had provided for reproducing this issue. 

David already mentioned steps to reproduce the issue in the beginning of this issue. Some notes from customer about running this app.
1) The new image.jar will execute forever and hang there unless you stop this app from opsManager or CLI. 
2) Please use attached file manifest.yml to push the app onto PCF. It defines the way of health check it uses.

Please l

et me know if this is enough for you to do further troubleshooting or any more info is needed.

**Comment by nebhale** [comment]
Without the source code it's difficult to know for sure, but I suspect the issue is that this is a font issue.  The fonts available to the JVM are (I believe) dictated by the stemcell/rootfs.  What font are you choosing to render the text and are is it available on the Linux image in the container?

**Comment by youngm** [comment]
@scottgai @nebhale we had similar issues with our applications.  The fonts provided in the rootFS are limited in their unicode support.  To work around this we embedded fonts in our application and on startup copy the fonts into the $HOME/.fonts directory (which for a running application is `/home/vcap/app/.fonts`).

Otherwise from my experience this is a rootfs issue not a buildpack issue.  It would probably be good for the rootfs to provide a open more fully unicode supported set of fonts if such a font exists.

**Comment by youngm** [comment]
Actually thinking back this issue wasn't java generating the pdfs but rather https://wkhtmltopdf.org/ generating pdfs.  So, perhaps adding system fonts the way we did might not be all that needs to happen for java to be able to utilize more fonts.  So, simply adding more system fonts may not be the end of the story.

**Comment by dgodd** [comment]
@youngm The problem with providing more fonts is which ones? Remembering that any semi decent unicode font is going to be around 10M in size. To the best of my knowledge there isn't a single unicode font which would support all of unicode. Can anyone on this thread suggest a single font which would be good for everyone? or even two in combination?

**Comment by nebhale** [comment]
ref: https://github.com/cloudfoundry/cflinuxfs2/issues/46#issuecomment-366996143

**Comment by scottgai** [comment]
@sclevine @dgodd @nebhale @youngm 
Thanks for the comments. To utilize `.profile` the PCF application needs to configure Pre-Runtime hooks, right? 
According to this [doc](https://docs.pivotal.io/pivotalcf/2-0/devguide/deploy-apps/deploy-app.html#profile): The Java buildpack does not support pre-runtime hooks. 
Is this statement still true? If so any idea about how to embed font into the Java app and copy it local font dir before starting app?

**Comment by scottgai** [comment]
I just downloaded font file `TraditionalChineseFonts.ttf` and manually put it to `/home/vcap/app/.local/share/fonts/` and `/home/vcap/app/.fonts`. Then run the jar file inside of app container manually to generate the image file. However it's still not shown correct traditional Chinese characters in image. 
Wondering if I have done in a right way or there are some other special procedure to make the font file effect in a container?

**Comment by dgodd** [comment]
@scottgai Is there a reason you don't want to use the font specifically in the java code? eg. from assets? something like 
```
GraphicsEnvironment ge = 
         GraphicsEnvironment.getLocalGraphicsEnvironment();
     ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("A.ttf")));
```

**Comment by youngm** [comment]
@scottgai If by "manually generate the image file" you mean sshed into the container.  If you notice when you ssh into a container your $HOME is /home/vcap not /home/vcap/app.  Try changing your home to /home/vcap/app or put the font in /home/vcap while sshed into a container and try again.

**Comment by scottgai** [comment]
Just FYI. The reported issue had been resolved by embedding the font into our application as assets. Thanks to everyone for the help!

**Comment by yhjhoo** [comment]
> @scottgai @nebhale we had similar issues with our applications who where generating PDFs. The fonts provided in the rootFS are limited in their unicode support. To work around this we embedded fonts in our application and on startup copy the fonts into the $HOME/.fonts directory (which for a running application is `/home/vcap/app/.fonts`).
> 
> Otherwise from my experience this is a rootfs issue not a buildpack issue. It would probably be good for the rootfs to provide a open more fully unicode supported set of fonts if such a font exists.

How do you copy fonts to this folder?
