### ISSUE TITLE
Custom private and trusted certificates

### ISSUE THREAD

**Issue by PatrikSteuer** [cloudfoundry/java-buildpack#558]
## Requirement
Custom private and trusted certificates should be provided based on our deployments. They shouldn't be part of the war/jar provided. These certificates are used in our use case for the saml communication between our app and an identity provider. 

### Possible implementations
1. fork java buildpack and add different keystores.
2. create user provided service with private and trusted certificates, which than will be added to a jks, which will be provided within the container

#### The second approach has following advantages:
- Easy to consume
- Treat certificates like credentials
- Easy exchange and control of provided certificates

Is it worth to investigate into such a feature?

**Comment by nebhale** [comment]
I think it is useful, especially if it's tied to a service broker that could be used for the same credential information.  There are two big issues as I see it.

1.  You're effectively putting private keys in an environment variable.  Those keys either won't have a password attached to them, or the password will be in the same environment variable.  There are certain organizations where this is a non-starter.
1.  This has no mechanism for key rotation.  Effectively, you **must** restage (and possibly even unbind/rebind) in order to rotate the key and certificate presented in this way.  This isn't a great user experience and one that Diego Instance Identity doesn't suffer from.

**Comment by konstantinblaesi** [comment]
https://github.com/pivotalservices/keystore-utility can read base64 encoded key stores from an environment variable.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
