### ISSUE TITLE
bin/supply for better multi buildpack support

### ISSUE THREAD

**Issue by samzilverberg** [cloudfoundry/java-buildpack#560]
atm it seems the java buildpack is only supported as a final buildpack. documenated in:
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-multi_buildpack.md

trying to include the buildpack as a non-final one results in an error:
`Error: one of the buildpacks chosen to supply dependencies does not support multi-buildpack apps`

which, as far as i understood, is thrown because there is no `bin/supply` script as described in:
https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html

are there any plans to have this bin/supply script soon?

**Comment by nebhale** [comment]
We're working on a move to the expanded buildpack contract including `/bin/finalize` and `/bin/supply` as the primary API (with `/bin/compile` delegating).  However, it's currently unclear what `/bin/supply` in a non-final buildpack would look like.  Specifically, unless the filesystem looks like an exploded JAR file, we do not do anything in the buildpack today.  In the case that the filesystem looks like an exploded JAR file, it'd also be the primary application being run, and the Java Buildpack would be the final buildpack anyway.

So the short answer is that while there will eventually be a `/bin/supply` script, allowing the buildpack to run as a non-final buildpack, it will probably not doing anything, which I'm guessing isn't what you expect.

**Comment by samzilverberg** [comment]
what i had in mind, was being able to use intermediary buildpacks to setup more runtimes + deps that the final app might need.

example: 
if a non-java app (ruby? nodejs? whatever!) needs to use some jar, then it'd be nice to be able to leverage the jave buildpack as a intermediary step to install the needed java version + any possible deps (maybe we're even building that jar), so that when the final app runs it has everything it needs.

this is of-course possible by creating custom buildpacks, but these tend to be very inflexible, with built-in non configurable runtime versions.
it'd be great if we could leverage the power of multi-buildpacks (with the already awesome buildpacks)  to create these kind of setups.

**Comment by nebhale** [comment]
The problem as I see it, is how to identify this behavior while also ensuring the `/bin/detect` works.  Given that there won’t be an exploded JAR on the file system (what we are looking for today) how exactly would the buildpack know that it needs to contribute a JRE?  What criteria can be satisfied in this case that wouldn’t cause `/bin/detect` to have false positives in other scenarios?

Secondly, because of the JRE’s defaults, running a JVM with the naive `java -jar ...` and no memory configuration will almost certainly cause the container memory limits to be exceeded and the container to be recycled.  How would one ensure that all callers of the this non-primary JRE properly configure it to stay within the bounds of the container, taking into account the variable amount of memory used by the primary runtime?  In addition, how do we ensure that users realize that a JVM [requires _hundreds_ of megabytes of memory](https://www.cloudfoundry.org/blog/just-released-java-buildpack-4-0/) to run safely.

In general, given today’s Diego structure, I’m quite skeptical that two processes can safely be run inside of a container without exceeding the memory limit of that container.  We’ve done a ton of work to ensure that a JVM will never exceed its container memory limit, but all of that is invalidated if there’s another process inside that container consuming memory.  We know from customer feedback that even with CF’s ability quickly restart the recycled instances, unexpected restart is a *huge* complaint and is unacceptable in many production scenarios.

To be clear, I totally understand the use-case here, I’m just unsure how we can safely deliver something that doesn’t leave open a strong possibility of a container recycle on usage.

**Comment by sclevine** [comment]
`/bin/detect` is only applied in the single-buildpack case.

Could we have `/bin/supply` provide the JRE + deps, and leave it to the (presumably non-Java) app to use the provided dependencies correctly in the container (with persistent sidecar processes explicitly unsupported until platform features make sidecars a better experience)?

**Comment by nebhale** [comment]
`/bin/detect` is only used in the single buildpack case, but there is an inherent linkage between it and `/bin/compile`.  To my way of thinking (and our implementation), `/bin/compile` only runs  in the same situations where `/bin/detect` would match; we literally use the same logic to determine what components will fire for all three phases.  Consider it a double check for when you specify the Java Buildpack accidentally with a Go application.

As it stands now, I'm uncomfortable with a contract where a buildpack would explicitly _not_ match `/bin/detect`, but would still attempt to modify a droplet during `/bin/compile`.  That seems like a sure way to mangle non-Java applications.

**Comment by sclevine** [comment]
If the Java buildpack ran as a non-final buildpack, only `/bin/supply` would be run. `/bin/supply` is not allowed to write to the app directory (only its dedicated sandbox directory in `<dep>/<idx>`), so it shouldn't mangle the user's app.

**Comment by nebhale** [comment]
But if `/bin/compile` is implemented as a delegation to `/bin/supply` and `/bin/finalize`, that separation doesn't exist.  That seems like a step back in support for the previous contract.

**Comment by sclevine** [comment]
What if `/bin/supply` provides just the JRE or JDK, and the rest of the process happens in `/bin/finalize`? I agree that anything else besides that (ex. installing app-specific dependencies) would be difficult to support given that the JBP works on an exploded JAR, and non-JAR apps would be painful to analyze.

@dgodd made a [buildpack](https://github.com/dgodd/jdk-buildpack) that just supplies the JDK for this purpose.

**Comment by samzilverberg** [comment]
I'm not familiar with all the internals of the java buildpack, but after following the conversation I understand its much more elaborate than I imagined.
From what I understand this kind of jre setup (+ maybe deps from maven gradel whatever) is easier and better done in a separate buildpack (& again, sadly all existing ones have hardcoded versions...).

to @nebhale concern about memory management: my 2 cents about this is that this kind of multibuildpack case is an advanced one, definitely not common, and anyone having to run this kind of case will have to consider the memory implications himself and plan accordingly!

where i work we have some 10% free time , so i hope to get the chance to write and contribute such a buildpack for installing java env (with configurtion of version and more...).

go ahead and close the issue if you want.

**Comment by kycrow32** [comment]
I know this is closed, but +1 for a way to include a jre for non-java applications (apps that will sometimes launch java to run jars).

**Comment by RoamEasy** [comment]
Is this still an open issue in the java-buildpack? It would be a nice feature to add.

**Comment by derTobsch** [comment]
It would be nice, if this would be possible because with the java buildpack as the non-final and e.g. the binary-buildpack as the final buildpack I could configure a jre and run a script that depends on jre.

**Comment by amaline** [comment]
Another +1 - would like to "run-task" with JRE even if primary buildpack is not Java.  For example using flyway to migrate database changes for a Node application.

**Comment by manitheja1** [comment]
Hi @nebhale 
we have a requirement where we could take the upstream java-buildpack  directly and have one customised buildpack which can configure the changes(like s3 resource links and appdynamics customization e.t.c) . So here when we push, first buildpack should be java buildpack because we have all the customization which has to be final buildpack.  I know it needs bin/supply if it is non final. is there a way ahead for this kind of setup to be performed?
