### ISSUE TITLE
JBP 4.x: Committed heap shows signs of memory leak

### ISSUE THREAD

**Issue by sivabalans** [cloudfoundry/java-buildpack#576]
Since moving to 4.x version of JBP, our spring boot apps are showing signs of memory leak where the committed heap is slowly consumed during an extended load test. Although it looks like a leak, there is no crash of the JVM. But the interval between full GCs are greatly reduced thus increasing the number  of full GCs over the same time period and thus increasing the CPU consumption as well. Below are some graphs that illustrates this:

Heap usage over 3 day time period:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/10453642/38824887-91fa0674-415f-11e8-8150-c28deb4bb54e.png">

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10453642/38824701-f0bff6d8-415e-11e8-82b2-cc5dfc51807b.png">

Old gen usage over the same time period:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/10453642/38824903-9d3fe7e2-415f-11e8-9c9b-b2cb50b48d89.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/10453642/38824723-03e2f878-415f-11e8-8b72-0e5718a3556c.png">

This test was started around 1.30pm on Thus, Apr 12. As you can see above, the heap usage seem to be fine until about 9am Apr 14. After that, the committed heap starts to get consumed at a  very rapid pace until it becomes equal to "used space". Then it continues to work fine except for the fact that the number of full GCs are happening at a much higher rate with a larger CPU consumption as you can see below:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/10453642/38825037-0d1c637e-4160-11e8-8513-fa2e6079c55e.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/10453642/38825055-1ba89278-4160-11e8-8e4a-b9c97dfce411.png">

We did not notice this behavior prior to JBP 4.x. We have checked the heap dumps and our code and we could not find any reason as to why the committed heap can leak memory. It also does not seem to be a leak as the JVM does not crash. 

We are trying to understand if this behavior of JVM is expected and what might be causing this behavior of committed heap. We are pushing the app with a memory size of 2GB. Everything else is default including the JBP values and memory calculator. 

P.S 1: the load on the service was pretty much constant throughout the test as you can see below:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/10453642/38825278-d67d499a-4160-11e8-9245-d2c83eb1c3fb.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/10453642/38825293-e14a8a5e-4160-11e8-80b6-92d06b0cbbb7.png">

P.S 2: Tested with various version of JBP. 4.6, 4.8 and 4.10 and they all exhibit similar behavior. The same codebase running on JBP 3.9  does not exhibit this behavior.

**Comment by nebhale** [comment]
The Java Buildpack isn't likely to be contributing anything that affects memory in any way.  In fact, nearly all of the work it does happens at staging time (before the process even starts) and what it contributes at runtime is almost exclusively limited to configuration of container at startup.

This is not to say that we cannot possibly have contributed a leak, just that it's unlikely.  Hooking in a profiler and seeing what creates the garbage that eventually gets collected would be a good start, as it would indicate if it is something we're contributing.

Beyond that, the biggest thing in 4.x that _might_ contribute to this is that we no longer set the start memory configuration (e.g. `-Xss`) in our configuration. This means that the GC profile is significantly different between 3.x and 4.x (for example, first GC's happen much earlier, and more often since they always happen before growing the allocated heap).  I'm not sure if that's what happening here, but it could be a contributor.

To really get a grip on what the change is, I'd start by getting a profiler on the application and understanding what's causing the garbage growth and triggering the GC's regularly.  We can then decide if there's something in the buildpack that's causing this issue.

**Comment by sivabalans** [comment]
@nebhale, thanks for your input. Using a profiler is not an option as none of the custom ports on our CF installation is open. So the next best option was to get a heapdump of the service when the committed heap and used heap lines merged. When we analyzed the heapdump, we did not find any leak suspects. 
I agree with you that the JBP itself may not be contributing to the leak. But the behavior of the heap seems to change significantly after about 36 to 48 hours into the test. That seem to be the mystery and was wondering if you guys had noticed this in any of your JBP testing for extended period of time with a springboot app.

**Comment by sivabalans** [comment]
@nebhale - Yes, we cannot use cf ssh. Thanks for your support on this. I will try to poll this issue in the CF community to see if anyone else has come across this. I will also try to collect more evidence and will update this issue.

**Comment by nebhale** [comment]
Sounds good.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
