### ISSUE TITLE
inconsistent CF_INSTANCE_IP value before and after JBP release callback

### ISSUE THREAD

**Issue by fwanggg** [cloudfoundry/java-buildpack#577]
I am extending JBP 4.8.

during the _release_ callback, i am trying to get **CF_INSTANCE_IP** 
`env = @application.environment['CF_INSTANCE_IP']`
When there are more than 1  diego cells. _env_ is inconsistent with the actual CF_INSTANCE_IP after the container is fully up. it looks like CF_INSTANCE_IP is always set to the IP of the **first** diego cell at the time of the _release_ callback. Only after the container is fully started up, i can see CF_INSTANCE_IP is updated and set to correct value.
`cf ssh myapp`
`env | grep CF_INSTANCE_IP    // this gives correct answer`

If there is only 1 diego cell, it seems that CF_INSTANCE_IP are consistent before and after container fully comes up.

I've tried to restage the app OR remove and re-push the app. I got same result.

At the time of the _release_ callback, i would expect CF_INSTANCE_IP to be correctly set on application because the value should be ready by then.

I think this is an issue. if not please let me know what to expect and how can i get accurate environment variables of the application from inside my JBP extension.

**Comment by nebhale** [comment]
This isn’t a bug, this is working as designed.  Staging happens in a container, but there is no guarantee that that container is used for running the application.  You cannot resolve any container-specific environment variable as part of staging because every time the droplet is put into a new container, that data might change.  Remember that a droplet is staged once, and your application is run in a container, without changing that droplet hundreds or even thousands of times, across all the cells in the platform.

In order to get container-specific environment data, you must reference that data at runtime.  So for example `System.getEnv(“CF_INSTANCE_IP”)` inside your application always returns that value, resolved at runtime rather than staging.

**Comment by fwanggg** [comment]
ok. i understand it now. 
"CF_INSTANCE_IP" that i get in JBP's release is the host machine's IP of the container that is used to do the staging(which happens to be the first diego cell) NOT the actual container that runs the application(which in my case a separate diego cell).  Correct me if i am wrong, otherwise you can close the issue i think.

**Comment by nebhale** [comment]
The [docs](https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-IP) state that it’s the IP address of the VM that the Diego cell is running on. So in a single-cell scenario, all containers run on the same cell, same VM, and same IP. In a multi-cell scenario, heuristics come into play and containers start in multiple cells, multiple VMs, and multiple IP addresses.
