### ISSUE TITLE
service upgrade question

### ISSUE THREAD

**Issue by fwanggg** [cloudfoundry/java-buildpack#579]
I know it only takes a cf restage for application to be physically bound to the service. 

Sometimes a PCF user would want to upgrade a bound service to a newer version. Let's assume the JBP extension of the service uses VersionDependencyComponent::download_zip to download the zip file and everything is working as expected i.e. JBP and the extension and the artifact hosting server has the correct index.yml etc...

In the case of upgrade, assume _index.yml_ on the artifact hosting server has a newer entry and a newer artifact, **is it true that the customer also just need to do a `cf restage`  to get the newer version of the service. Or they have to remove the app first and rebind and re push to get the newer version?**

I am asking because based on my observation it's the later case where you need to remove/rebind to get the new service. I am not sure if it's an user error or expected behavior. The answer to this question will help me figure that out.

**Comment by nebhale** [comment]
Dependency version resolution is done on each run of staging.  What you're probably running into is the fact that downloading of dependency metadata (`/index.yml`) and the dependencies themselves practice avoidance based on `Last-Modified/If-Modified-Since` and `Etag/If-None-Match`.  Requests for artifacts are made with the previous values and if a `304` is received the buildpack assumes that the previously cached version is up to date.

It sounds like you're running into an issue where whatever is serving your `index.yml` is responding with a 304 even though you've changed the file in some way so the buildpack is considering its cached copy of that file up to date.  You can validate this by enabling buildpack debug logging (`cf set-env <APP> JBP_LOG_LEVEL DEBUG`) and you'll see the requests for your file and the response that is received.

**Comment by fwanggg** [comment]
you nailed it. it seems that the file server we locally used for qa cached index.yml.

**Comment by nebhale** [comment]
Great to hear that you found the problem.
