### ISSUE TITLE
400 Bad request errors for restful services

### ISSUE THREAD

**Issue by dumitru-gudima** [cloudfoundry/java-buildpack#593]
Not sure why but some of our services return 400 bad request if using latest javabuildpack#v4.12. 
It's a monolithic spring app (.war) 
RequestMapping (Spring Framework 5.0.6.RELEASE API)

**Comment by nebhale** [comment]
In order to attempt a diagnosis, I'll need more information that just the status code.  Is the 400 coming from the router or your application?  Is the application creating a stack trace indicating that something is going wrong?  Does the Spring Framework startup logging indicate that all of the endpoints you think should be mapped are actually being mapped?
