### ISSUE TITLE
Cannot push additional configs

### ISSUE THREAD

**Issue by artursmolarek** [cloudfoundry/java-buildpack#608]
My java applications requires an additional .json config in order to start.
Unfortunately I'm not able to push it because buildpack throws an error when `path` is set as a directory. What need to be done in order to push something more than only single jar file?

```
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation. >
   No container can run this application. Please ensure that you've pushed a valid JVM artifact or artifacts using the -p command line argument or path manifest entry. Information about valid JVM artifacts can be found at https://github.com/cloudfoundry/java-buildpack#additional-documentation.
```

**Comment by nebhale** [comment]
Cloud Founrdy presents buildpacks with a directory of the contents pushed by the user.  If the user pushes an archive artifact (e.g. a JAR file) the buildpack is presented with an exploded archive on the filesystem.  The Java Buildpack expects to receive one of these exploded archive artifacts at all times in order to do its work.  If you push a directory containing a JSON configuration file and a JAR file, this directory structure is what is presented to the buildpack, and is not recognized as it is not an exploded archive.

In order to present the buildpack with a directory structure it recognizes, you’d need to include the JSON configuration file within the archive artifact itself.  I’d recommend putting it into `META-INF` as that directory cannot be accidentally exposed to the world via a Servlet.  Better yet, your application should adhere to [12 Factor](https://12factor.net) principals and [store configuration in the environment](https://12factor.net/config).
