### ISSUE TITLE
Jre 11 support in buildpack

### ISSUE THREAD

**Issue by hmlingesh** [cloudfoundry/java-buildpack#619]
Hello Team , 
Do you have any plan to integrate JRE 11 for openJDK and Oracle JDK , because JRE8 support going to end from community.

Regards
Lingesh M

**Comment by nebhale** [comment]
We do plan on offering Java 11 as soon as it goes GA.  [We've offered](https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/index.yml) Java 9 through its now completed lifecycle and Java 10 now as it goes through the same.  Once 11 has been released we'll make that available as well.

**Comment by hmlingesh** [comment]
Thanks Team !!!.

**Comment by keeganwitt** [comment]
I presume the buildpack will continue to track upstream OpenJDK, even though "LTS" releases will now only get 6 months of updates, so that it'll be a new OpenJDK version every 6 months?  Or do you plan to use something like [AdoptOpenJDK](https://adoptopenjdk.net/) builds that will backport security fixes into LTS releases and stick with LTS?
