### ISSUE TITLE
Expose prometheus exposition metrics endpoint

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/java-buildpack#622]
It would be great if the prometheus exposition metrics endpoint could be exposed and authenticated via oauth token. 

I think an easy way to do this would be to use the permissions endpoint on cloud controller detailed here: https://apidocs.cloudfoundry.org/3.4.0/apps/retrieving_permissions_on_a_app.html
and ensure the requester has access to sensitive data.

**Comment by kitemongerer** [comment]
@nebhale thoughts on the above?

**Comment by nebhale** [comment]
This isn't a change for the buildpack to make.  That endpoint exists because of support within Spring Boot for doing authentication on a Cloud Foundry-specific set of actuators, accessed by Pivotal Apps Manager.

My guess is that since the Prometheus endpoint is handled as a standard actuator, it is already exposed and secured using this same scheme.  The problem is, that the security model is inherently different.  Apps Manager runs on behalf of a user, so it uses a three-party OAuth (user, client, resource; implicit grant type).  For an automated scraper to access that endpoint though it's a two-party OAuth (client, resource; client credentials grant type).  In addition, a whole new set of authorities/grants need to be added to support one of these scrapers since they cannot reuse the extant Apps Manager client.
