### ISSUE TITLE
Class.getPackage() not working

### ISSUE THREAD

**Issue by dustpuppyNGTI** [cloudfoundry/java-buildpack#630]
I want to use the Class.getPackage().getImplementation*() feature to read some configuration information from the manifest.mf in the jar. This works fine in a regular jar but fails when I push this jar to CF.

The error I get is this:

    2018-09-11T14:12:21.18+0200 [APP/PROC/WEB/0] ERR Package: package test.testapp
    2018-09-11T14:12:21.18+0200 [APP/PROC/WEB/0] ERR Title  : null
    2018-09-11T14:12:21.18+0200 [APP/PROC/WEB/0] ERR Vendor : null
    2018-09-11T14:12:21.18+0200 [APP/PROC/WEB/0] ERR Version: null

Running the same jar locally gets me the right information:

    $ java -jar target/testapp.jar 
    Package: package test.testapp
    Title  : testapp
    Vendor : test
    Version: 0.3

I created a basic project here that shows the problem: https://github.com/dustpuppyNGTI/CF-JavaBuild-getPackage-bug

**Comment by nebhale** [comment]
There's no problem with the JRE here.  Rather it's that your application is run as an exploded JAR file within the container and *no* JRE properly interprets the `MANIFEST.MF` entries in that situation.  Given that this has been the way Cloud Foundry has behaved since it's inception, we won't be making any changes to the deployment behavior.
