### ISSUE TITLE
java is not detecting all processors in our cloud foundry environment

### ISSUE THREAD

**Issue by grimmpp** [cloudfoundry/java-buildpack#650]
Hello,

when I run `Runtime.getRuntime().availableProcessors();` in an app in our Cloud Foundry the answer is 1 although there are 16 available processors which I can list by using `cat /proc/cpuinfo | grep processor`.

Would it be possible to set the amount of processors always as argument within the java start command like
`-XX:ActiveProcessorCount=$(nproc)`
?

**Comment by nebhale** [comment]
Java 10 is where this [shows up natively](
https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/), so we can add this for all pre-10 versions.

**Comment by shakuzen** [comment]
Most (or all?) of those docker container detection changes were [backported to the recent Java 8 update 191](https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html#JDK-8146115).
The `XX:ActiveProcessorCount` option seems to have been added with that update.
> In addition, this change adds a JVM option that provides the ability to specify the number of CPUs that the JVM will use:
>
> `-XX:ActiveProcessorCount=count`

So will the change made have any effect before that update on Java 8?

I think this issue is reporting that the CPU count is returned as 1 always WITH the container detection support. At least this is my findings after checking some of our applications (8u192 and 10.0.2) in response to seeing this issue. Before 8u191, they detect the cell's CPU count, after they always detect 1 CPU.
While the improved container support is only specifically tested on docker, my understanding is that it should work with cgroup based containers. I think it is worth looking into why it isn't working out-of-the-box with buildpack containers. Otherwise, the `-XX:ActiveProcessorCount=$(nproc)` option may have to be added with all versions of Java, even if it only helps with versions that recognize the option.

**Comment by nebhale** [comment]
> So will the change made have any effect before that update on Java 8?

We've been shipping `_191` since October 17, so the update to the command follows the addition of support to the JRE.  We should be fine here as far as compatibility (testing seems to indicate so).

> I think this issue is reporting that the CPU count is returned as 1 always WITH the container detection support.

Yeah, I'm seeing the same thing with both our 11, and AdoptOpenJDK's 11.  I'll start going around the houses here at CF HQ to see if we can figure out where the disconnect is.

/cc @emalm @julz

**Comment by nebhale** [comment]
After a morning investigating this, it turns out to be yet another example of OpenJDK's half-assed container support.  Let's go to the code!

Available processors is an [algorithm](http://hg.openjdk.java.net/jdk/jdk/rev/7f22774a5f42#l4.516) that calculates the minimum of `os::Linux::active_processor_count()`, `ceil(cpu.shares/1024)` (if set), and `ceil(cpu.cfs_quota_us/cpu.rt_period_us)` (if set).  "If set" is determined by a number greater than `-1` for the values.

So if we look at a Diego, we see `cpu.shares=122` (and in newer versions `1056`, container memory + 32 for Envoy), and `cpu.cfs_quota_us=-1`.  Therefore, you get the minimum of 4, 1, and 4, resulting in 1.  What's weird is that if you look at Docker, you see `cpu.shares=1024` which should once again get us the minimum of 4, 1, and 4, but for some reason it results in 4.

The reason is this [little slice of WTF](http://hg.openjdk.java.net/jdk/jdk/rev/7f22774a5f42#l4.589), wherein, if the value for `cpu.shares` is `1024`, **the value returned is -1!**.  Nevermind that 1024 is a magic number in the code (they've abstracted it to `PER_CPU_SHARES` in [other places](http://hg.openjdk.java.net/jdk/jdk/rev/7f22774a5f42#l4.43)) but it also isn't in any way a constant.  CPU shares is a relative number so 122 is as reasonable a value as 1056 or 1024 or anything else.  It's used by the system as a relative weight, so thinking that 1024 somehow maps to a "logical processor" is insane.  Especially since the CPU count, based on cpuset is available (`cpuset.cpus`).

Therefore, there is no chance that this will ever be calculated correctly (each scheduler sets the share values to something it cares about to allow relative weighting, not multiples of 24) so we'll simply set it at all times instead of only for Java 10 and below.

Sigh.

**Comment by shakuzen** [comment]
Thanks for the investigation and quick turnaround, Ben.

Quite the surprising implementation in Java for CPU shares, indeed.

Now with setting `-XX:ActiveProcessorCount=$(nproc)` I think we are back to the behavior before Java's container support - using the cell's CPU core count. AFAIK, in Cloud Foundry this means that the JVM will detect the effective maximum CPU cores available to the container (when nothing else on the cell is using the CPU). I thought it would be better for it to use the minimum (guaranteed even when every container wants more CPU than its share) CPU core shares, so that under peak load (for an entire cell), the JVM operates with the right assumption of cores usable.
However, with tickets like [JDK-8197867](https://bugs.openjdk.java.net/browse/JDK-8197867), I'm not so sure what's best, because they went with maximum CPU cores by default when CPU shares and quotas are both used.

**Comment by nebhale** [comment]
This is where the corruption of shares and count is at its worst.  Cores determines parllelism, so I think using the max cores is correct.  If your share is low, then the container scheduler limits how much of each of those CPUs you use, but this is no different than a base-metal system with multiple processes loading up the CPUs.  At the very least, this is a predictable behavior that can be easily reasoned about.
