### ISSUE TITLE
JBP doesn't download the latest artifacts in v4.16?

### ISSUE THREAD

**Issue by fwanggg** [cloudfoundry/java-buildpack#678]
we tried JBP 4.17 and master. The behavior is JBP downloads the latest release of artifacts from the external file server.
But in 4.16, it looks like JBP downloads the first one in index.yml.
We just want to make sure if such bug exist in 4.16 and was fixed later perhaps. (I couldn't find one matching issue though).

**Comment by nebhale** [comment]
[Online buildpacks](
https://github.com/cloudfoundry/java-buildpack/blob/master/config/riverbed_appinternals_agent.yml#L18) download the latest version, by wildcard, from the contents of `index.yml`.  [Tagged versions of online buildpacks](
https://github.com/cloudfoundry/java-buildpack/blob/v4.16/config/riverbed_appinternals_agent.yml#L18) fix the version for build reproducibility but still download from the internet at runtime.  [Offline Buildpacks](
https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.16) fix the version and include the binary in the package so that download from the internet is not required.

This is the way that the buildpack has worked for five years and no bug has ever been found in either the version resolution or release version pining during that time.
