### ISSUE TITLE
Env Variables with dots (".") do not work with cflinuxfs3  

### ISSUE THREAD

**Issue by stiliyanv** [cloudfoundry/java-buildpack#687]
Hi java-buildpack Team,

When I use simple Java web application using `cflinuxfs2` stack with the following env configuration in the `manifest.yml`...

```yml
...
env:
  test.env: "test.env"
...
```

...everything works fine and the env variable can be retrieved (using `System.getenv()`).

Unfortunately, this is not the case when using the new `cflinuxfs3` stack. This variable is no more available in the environment variables. It looks that this issue is somehow related to the dot (`.`) in the variable name, because if I use underscore (`_`) instead of dot (`.`) (for example:  test_env: "test.env"), it works fine.

Any idea what could be changed between those two stacks that causes this behaviour and how it could be fixed?

Best regards,
Stiliyan

**Comment by nebhale** [comment]
Officially `bash` does not support dots in environment variable names ([an example](https://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it) although not authoritative).  I believe what you're seeing is that we're upgrading from `trusty` (`cflinuxfs2`) with an ancient version of `bash` to `bionic` (`cflinuxfs3`) means that the newer version of `bash` is now enforcing this limitation.

**Comment by mohanbabubb** [comment]
@nebhale Is it same for 'test.env' ( closed with single quotes ) also?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by keviningvalson** [comment]
I have isolated this issue further.

War files that are presented to the buildpack will launch with 
exec $PWD/.java-buildpack/tomcat/bin/catalina.sh run

Since #!/bin/sh is linked to dash in cflinuxfs3
/bin/sh -> dash
and takes a strong opinion on environment variables it removes any env vars that are not POSIX compliant

Jar files that are presented to the buildpack will launch with
eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java
and maintain all environment variables.

As such, there is an inconsistency in the handling of env vars by the java buildpack depending on the packaging type.

In the context of stiliyan's app I expect that it would work as a jar but fail as a war.

I have created an isolated test case reviewing org.springframework.beans.factory.config.PropertyPlaceholderConfigurer confirming that the env scope is reduced as seen by value = System.getenv(key); in resolveSystemProperty(String key)
