### ISSUE TITLE
How to get the latest version of skywalking agent 

### ISSUE THREAD

**Issue by Anand0583** [cloudfoundry/java-buildpack#714]
Hello Team,

When I create a skywalking-agent service and provide the tags of sky-walking-agent=6.0.0_GA, then too the older version of skywalking-agent is only getting downloaded which is 3.2.6.

https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-sky_walking_agent.md

When looked into the 

https://github.com/cloudfoundry/java-buildpack/blob/master/config/sky_walking_agent.yml

version is mentioned as 3+ is there any way to override this setting and get to latest version of 6.0.0_GA

https://download.run.pivotal.io/sky-walking/index.yml
6.0.0_GA: https://java-buildpack.cloudfoundry.org/sky-walking/sky-walking-6.0.0-GA.tar.gz

Thanks,
Anand.

**Comment by nebhale** [comment]
Upgrading to 6.0.0 is non-trivial since the packaging structure and operation of the agent have drastically changed from when the integration was added.  Someone will need to submit a PR to update the integration before we can allow the upgrade to happen.  Once that is in place, the following release will ship 6.0.0.

**Comment by Anand0583** [comment]
@nebhale can you please let me know when this is being planned.
