### ISSUE TITLE
unable to find jcmd in latest java buildpack

### ISSUE THREAD

**Issue by indusankar89** [cloudfoundry/java-buildpack#735]
Hi,

I am unable to find jcmd in the latest java buildpack. It was available in java buildpack 4.16.
PFB screenshots for the same. 
Latest buildpack:
![java_latest](https://user-images.githubusercontent.com/18476413/60256447-282aa580-98ef-11e9-81af-72628620758b.PNG)
Java 4.16:
![java_4 16](https://user-images.githubusercontent.com/18476413/60256448-282aa580-98ef-11e9-8de9-b108cb224dee.PNG)

**Comment by nebhale** [comment]
After a recent legal review, it was pointed out that the JREs that we had been shipping were not "perfect" JRE's; they [included tools](https://github.com/cloudfoundry/java-buildpack/issues/146) that only existed in JDKs. In order to meet our legal obligations, all future JREs must be built as "perfect" JREs with only the tools that ship with normal JREs.
