### ISSUE TITLE
app staging failed in buildpack compile phase

### ISSUE THREAD

**Issue by Anil2703** [cloudfoundry/java-buildpack#740]
![image](https://user-images.githubusercontent.com/39698174/62835966-d9a55080-bc7b-11e9-9157-4865c770c9cd.png)

can u pls me with the above issue?

**Comment by nebhale** [comment]
As the error says, you've pushed something that is not a valid JVM artifact.  You can check the [documentation](https://github.com/cloudfoundry/java-buildpack#additional-documentation) for a list of containers and what kind of artifacts they'll run, but typically this is caused by pushing something other than the compiled JAR.

**Comment by Anil2703** [comment]
i found the solution for this.
previously i m  trying the push the app from the project folder itself, but now when i went a step back that is cmd[cd..], then the app push is successfull. thanks a lot for your response
