### ISSUE TITLE
Trusted custom RootCAs

### ISSUE THREAD

**Issue by Sosby** [cloudfoundry/java-buildpack#746]
Needing some direction or better understanding of how rootCA's are pulled from `/etc/ssl/certs/ca-certificates`.  We've recently added various custom certs ( configured within Ops Manager director tile ) and when ssh'd onto a droplet we can see those certs in the ca-certificates file.  However, when I list the contents of the java keystore using the below commands the custom cert is not listed.  

```
/home/vcap/app/.java-buildpack/open_jdk_jre/bin/keytool -list -v -keystore /home/vcap/app/.java-buildpack/open_jdk_jre/lib/security/cacerts
```

Now, if I perform the following everything works just fine. 

```
home/vcap/app/.java-buildpack/open_jdk_jre/bin/keytool -import -file classes/static/customCA.cer -v -keystore /home/vcap/app/.java-buildpack/open_jdk_jre/lib/security/cacerts
```

Am I misunderstanding the behavior of the buildpack?  I can see in the logs the following so I'm assuming its pulling the contents from `/etc/ssl...`:

```
Adding System Trust Manager
Adding TrustManager for /etc/ssl/certs/ca-certificates.crt
Start watching /etc/ssl/certs/ca-certificates.crt
Initialized TrustManager for /etc/ssl/certs/ca-certificates.crt
```

Any help would be much appreciated.  Thanks!

**Comment by nebhale** [comment]
The Container Security Provider does not modify any keystore on the file system as those are only read on startup of the JVM.  Instead, it [contributes in-memory `Trust-` and `KeyManager`s](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_security_provider.md#security-provider).  This allows those `-Manager`s to watch for changes to the files on the filesystem (say rotation of container identity) and dynamically reload the cryptographic contents of the JVM without restarting the process.

So the only place where the contents of `/etc/ssl/certs/ca-certificates.crt` are ever loaded is in memory as a second `TrustManager` (after the system `TrustManager`) in a delegate chain.  The system `TrustManager` (either the default one from `$JAVA_HOME/lib/security/cacerts` or the one configured via `-Djavax.net.ssl...`) is given first opportunity to trust a server's TLS certificate.  Only if that `TrustManager` declines does the `/etc/ssl/certs/ca-certificates.crt`-based `TrustManager` get an opportunity to trust.  If it can (because a BOSH-managed certificate is found), then the TLS connection proceeds; if it doesn't the connection does not.

**Comment by Scoobed** [comment]
I have a same question.  I tried to follow the logic above.  Let me provide a scenario where the above logic does not work.  In my cause, we are doing Mongo SSL and it is signed by my companies root certificate which is in the container which if following the above logic above the only way for it work correctly because of these rolling bosh certificates is to override the keystore with a custom on. We can see exactly that using your java-test-application repo

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
