### ISSUE TITLE
tomcat/jdk version is hardcoded

### ISSUE THREAD

**Issue by aadyyb** [cloudfoundry/java-buildpack#792]
we are replicating repo for airgap usage, we found the tomcat version is hardcoded and it becomes outdated before the next release.

For example 9.0.30 is hardcoded in v4.28  (https://github.com/cloudfoundry/java-buildpack/blob/v4.28/config/tomcat.yml#L19)but the latest in the repo is 9.0.33.

We want to delete older tomcat in confident. Is there a reason not to use version like `9.+` in master?

**Comment by nebhale** [comment]
[Tagged versions](https://github.com/cloudfoundry/java-buildpack/blob/v4.28/config/tomcat.yml#L19) of the buildpack pin their versions and check them into source control in order to ensure build reproducibility, while [`master` does not](https://github.com/cloudfoundry/java-buildpack/blob/master/config/tomcat.yml#L19).  If you are comfortable following along with ever increasing versions of Tomcat, there's no need to pin it.
