### ISSUE TITLE
java-buildpack incompatible with the use of cf scale -MEMORY cmd

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/java-buildpack#8]
The java-buildpack statically applies memory heuristics at staging time, i.e. includes the -Xmx option in the start cmd. As a result, if a user is using the `cf scale -memory` command to decrease the memory, the JVM will still try to allocate up to the initial memory account. The jvm will then exceed the memory limit and be killed by the warden container.

Possible workaround: apply the memory heuristics within the droplet using the http://docs.cloudfoundry.com/docs/using/deploying-apps/environment-variable.html#VCAP_APPLICATION limits entry.

**Comment by youngm** [comment]
@nebhale We're implementing some auto-scale behaviour and ran into this restage issue again.  It is one thing to know you must restage when scaling a java app via the CLI.  But when a user is setting up auto scale rules, asking them to restage or restart depending on the buildpack used is yet another annoying side effect of staging time memory heuristics.

I've never been a fan of this behaviour and the complexities it propagates to the user.  Auto scale rules is yet another example of this complexity pushed to the user.  I hope that you guys haven't given up completely on a startup time memory heuristics solution sometime in the future.

**Comment by youngm** [comment]
@nebhale I read through @glyn 's explanation for why this doesn't work.  I don't recall, did we have a functional loggregator when this was last attempted?  I don't see why memcalc cannot simply log to stdout that there is not enough memory to run the app then give the jvm 0 heap and let it fail?

Seems to me this makes the java buildpack no different from any other buildpack.  If I scale node down too small it will fail to start and I must look at loggregator to see who.

Thoughts?

**Comment by nebhale** [comment]
@youngm  So if we take a look at the automatic memory-sizing feature we see that it's very existence is an artifact of the JVM.  The reason that the Java Buildpack (err, JVM buildpack) is different than all the rest is that it's the only setup where the process doesn't use all allocated memory by default.  If you look at Ruby, Node, etc. the process will happily use as much memory as it can get a hold of.  The JVM on the other hand will only use its default (`64M` I think?), unless otherwise specified.

So, if we assume that a calculation _must_ be made to ensure that people paying for a `2G` instance have a JVM that uses `2G`, the question is when do we calculate it.  The inputs for that calculation (i.e. `$MEMORY_LIMIT`) are available both at staging and startup so both are options.  Staging was deemed to be the best choice because the code to calculate the memory configuration is sizable and because we cannot depend on Ruby being available at runtime unless we add it to the droplet.

The memory calculation consists of [7 files with 443 SLOC](https://github.com/cloudfoundry/java-buildpack/tree/master/lib/java_buildpack/jre/memory).  That's a sizable amount of Ruby to be putting into Java/JVM application's startup routine.  Certainly any concerns about errors being reported are lessened these days, although the failure mode where staging results in `Down`, `Down`, `Down`, followed by `cf logs` isn't as nice as a directly printed failure at staging and a refusal to start.

The stronger argument against moving the functionality relates to the Ruby runtime.  At the moment, there is no guarantee (by which I mean contractual documentation) that a Ruby runtime is available to _all_ applications at runtime.  Even if we accept that there is in practice, it's problematic to use it because we have no idea what version it is, and what the upgrade cycle for that version is, and whether it will be around tomorrow.  So that leads us into the situation of adding a Ruby to a Java/JVM droplet just so that we can make the memory calculation.  At the moment the Ruby runtime is running at `32.1M` (for comparison the JVM is running at `39.2`) so that seems like a pretty hard pill to swallow.

I'm open to arguments on this, and I totally understand your complaints about knowing whether to `restart` or `restage` (note that we also require `restage` for service changes which other buildpacks don't necessarily need).  Keep in mind that the JVM and the functionality of the Java Buildpack are both quite different from the other runtimes and buildpacks which is what leads to these differences in behaviors.

**Comment by glyn** [comment]
One *option* would be to write a Go program to do the calculation at runtime and include that program in the droplet. Then there would be no dependencies to worry about, unlike with Ruby. The inputs to the program could be written into a file by the buildpack and then read by the Go program at runtime. (This is equivalent to the hair-brained scheme we discussed months ago of including a shell script in the droplet to do the calculation and which we rejected this because of the lack of precision in shell arithmetic. Thankfully Go has suitable arithmetic support.)

**Comment by youngm** [comment]
@nebhale Thanks for being willing to open the topic up again.  I understand how the JVM makes this difficult.  However, I think wherever possible if we can make the java buildpack function similar to the other buildpacks it would be a win for the platform.

I've been doing some thinking and combined with @glyn 's idea I'd like to propose a candidate solution to discuss.

* Continue to do memory heuristics calculations during staging.  If we can find it a memory setting is going to fail during runtime this would allow us to tell the user more directly.  Plus other calculations and validations would still need to happen at staging anyway, like ensuring illegal jvm args are not used.

* Create a Go or other small native binary application to do the memory heuristics calculation.

* It appears that loggregator app startup loging was improved sometime after this spike was performed previously: https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/bgCvU04rrwc/2R0c8hZYXRUJ

* The memory heuristics app should print the detected memory settings to loggregator if successful.

* If not enough memory is detected then set the heap to 0 or find some other consistent way to crash the jvm and print a bunch of diagnostics and reasons for the failure.

* It may be necessary until diego is common to have the memory app sleep for a second or 2 on failure to ensure that the dea logging agent is attached and will get the failure report. https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/2acNlom2MHc/PSERnltc-rkJ

I think with what is proposed above we:
* No longer have the ruby on dea agents issue
* Apps will know at staging time if they set an invalid memory setting
* Apps will be able to scale memory up and down without restaging.
* If memory is set too low then the app will fail on restart just like all the other buildpacks today, that said the point of scale down failure will be much higher than most other platforms.

Thoughts?

**Comment by glyn** [comment]
I think that solution might work, although it would depend very much on
whether diagnostics are captured properly during application startup. I
don't particularly like the idea of the memory heuristics application
having to sleep on failure because that seems flaky. How long would it need
to sleep to *guarantee* that the logs get reported? This seems like an
unpredictable value.

BTW if this is implemented, it *might* make sense also to call the memory
heuristics application at staging time rather than maintain the existing
duplicate Ruby code too.

On Tue, Jan 6, 2015 at 5:35 PM, Mike Youngstrom <notifications@github.com>
wrote:

> @nebhale <https://github.com/nebhale> Thanks for being willing to open
> the topic up again. I understand how the JVM makes this difficult. However,
> I think wherever possible if we can make the java buildpack function
> similar to the other buildpacks it would be a win for the platform.
>
> I've been doing some thinking and combined with @glyn
> <https://github.com/glyn> 's idea I'd like to propose a candidate
> solution to discuss.
>
>    -
>
>    Continue to do memory heuristics calculations during staging. If we
>    can find it a memory setting is going to fail during runtime this would
>    allow us to tell the user more directly. Plus other calculations and
>    validations would still need to happen at staging anyway, like ensuring
>    illegal jvm args are not used.
>    -
>
>    Create a Go or other small native binary application to do the memory
>    heuristics calculation.
>    -
>
>    It appears that loggregator app startup loging was improved sometime
>    after this spike was performed previously:
>    https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/bgCvU04rrwc/2R0c8hZYXRUJ
>    -
>
>    The memory heuristics app should print the detected memory settings to
>    loggregator if successful.
>    -
>
>    If not enough memory is detected then set the heap to 0 or find some
>    other consistent way to crash the jvm and print a bunch of diagnostics and
>    reasons for the failure.
>    -
>
>    It may be necessary until diego is common to have the memory app sleep
>    for a second or 2 on failure to ensure that the dea logging agent is
>    attached and will get the failure report.
>    https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/2acNlom2MHc/PSERnltc-rkJ
>
> I think with what is proposed above we:
>
>    - No longer have the ruby on dea agents issue
>    - Apps will know at staging time if they set an invalid memory setting
>    - Apps will be able to scale memory up and down without restaging.
>    - If memory is set too low then the app will fail on restart just like
>    all the other buildpacks today, that said the point of scale down failure
>    will be much higher than most other platforms.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/java-buildpack/issues/8#issuecomment-68900123>
> .
>



-- 
Regards,
Glyn

**Comment by youngm** [comment]
@glyn The sleep time is unfortunate but is a known issue and should be fixed in diego.  From my experience 1 second has always worked for me but some testing will be necessary.  Even if we set the delay to 5 seconds I don't think having to wait 5 seconds before loggregator gives you a good failure message would be too egregious and should be a reason to give up on runtime memory scaling.

I agree about using the same binary during staging and running.
