### ISSUE TITLE
Java buildpack URL not returned via cf cli

### ISSUE THREAD

**Issue by vorbidan** [cloudfoundry/java-buildpack#866]
Prior to java buildpack v4.32 , when one deploys a java app with manifest like:
```
...
buildpacks:
- https://github.com/cloudfoundry/java-buildpack.git#v4.28
...
```
the buildpack name is properly displayed with `cf app APP_NAME`:
```
...
last uploaded:     Mon 05 Apr 17:47:18 MDT 2021
stack:             cflinuxfs3
buildpacks:        https://github.com/cloudfoundry/java-buildpack.git#v4.28
...
```

Since v4.32, the result of `cf app APP_NAME` looks like this:
```
...
last uploaded:     Mon 05 Apr 17:49:58 MDT 2021
stack:             cflinuxfs3
buildpacks:        java
...
```

I believe it is related to change introduced in response to Issue #812

**Comment by vorbidan** [comment]
It is still possible to retrieve the exact buildpack reference with `cf curl /v2/apps/APP_GUID`

**Comment by dmikusa-pivotal** [comment]
@vorbidan Are you still seeing this issue? 

My understanding is that with #812 the JBP is not taking advantage of the v3 Cloud Controller API and how it stores the buildpack info, which is what we want to be doing going forward. I know this question has come up before and if I remember correctly, this was happening cause the cf cli was looking at the old info still (I could be wrong on that, again, it's been a while since this has come up).

If you're still seeing this, please try using both the latest v6 and v7 cf cli and let me know what you see. Thanks

**Comment by vorbidan** [comment]
Makes sense. I was seeing it with an older version of cf cli. Will try with v7 and let you know.
Thank you for replying!

**Comment by benjaminguttmann-avtq** [comment]
To me it looks like an issue with cf6 and cf7, cf7 provides information mentioned by @vorbidan , cf6 does not (anymore).

**Comment by dmikusa-pivotal** [comment]
Thanks for confirming!
