### ISSUE TITLE
Potential FileWatcher memory leak

### ISSUE THREAD

**Issue by yusmenrashidov** [cloudfoundry/java-buildpack#919]
Hello there,

I am deploying Spring Boot application using embedded Tomcat with mTLS enabled. I have created  a custom SSL configuration with the respective keystore and truststore configured. However,  when deploying the application it does not start. In the logs I have found the following errors :

```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server`
```

```
The web application [ROOT] appears to have started a thread named [file-watcher-ca-certificates.crt-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
 java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
 sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
 org.cloudfoundry.security.FileWatcher.run(FileWatcher.java:81)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
```

and

```
The web application [ROOT] appears to have started a thread named [Thread-3] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.fs.LinuxWatchService.poll(Native Method)
 sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
 sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
 java.lang.Thread.run(Thread.java:748)`
```

I have found a similar issues like this in #459 and #486 but they don't help me in resolving the problem. Is there a memory leak here and how could this be resolved or I am doing something wrong?

My stack:
java_buildpack-cached-cflinuxfs3-v4.43
Spring Boot 5.2.18
Tomcat 9.0.56

Thanks in advance.

**Comment by dmikusa-pivotal** [comment]
>The web application [XYZ] appears to have started a thread named [ABC] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

This is a message that Tomcat generates when an application context is being stopped. It is helpful in tracking down issues but it really only applies if you are doing hot-reloading with Apache Tomcat. When doing hot-reloading, the application is stopped & another is loaded. This stopping and starting of apps while the JVM continues can result in memory leaks, as the error says.

When the JVM exits, it doesn't matter. All memory is reclaimed by the OS. It's just a little bit of noise in your log files.  Because apps that run on CF always have the JVM, and the container too, terminated this really isn't an issue. It's just noise in your logs.

I'm honestly not surprised to see it happen because we go to great lengths to ensure that the thread does not terminate. This is because it's watching the instance id certificates and it's very important for the thread to continue running so that it updates the certificate when the certificate is rotated.

Hope that helps!

**Comment by yusmenrashidov** [comment]
Hi, @dmikusa-pivotal 
Thank you for your response. Could you give any advice on how we can overcome this behaviour? Do we have to perform some configuration changes in our application?

Thanks in advance

**Comment by dmikusa-pivotal** [comment]
If the application is crashing, it's not because of this. This is just output that Tomcat writes after it's already starting to shutdown. It's a red herring in this case. You'd want to look for other possible causes for your app crash.
